import React from 'react';
import { Zap, TrendingUp, Sparkles } from 'lucide-react';
import ViralScoreBadge from './ViralScoreBadge';
import type { AutoGeneratedClipSuggestion, VideoClip } from '../types/app';

interface ClipSuggestionsProps {
  aiSuggestions?: AutoGeneratedClipSuggestion[];
  trendingClips?: VideoClip[];
  onSelectSuggestion: (startTime: number, endTime: number, title: string) => void;
}

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}:${s.toString().padStart(2, '0')}`;
}

export default function ClipSuggestions({ aiSuggestions, trendingClips, onSelectSuggestion }: ClipSuggestionsProps) {
  const hasAI = aiSuggestions && aiSuggestions.length > 0;
  const hasTrending = trendingClips && trendingClips.length > 0;

  if (!hasAI && !hasTrending) return null;

  return (
    <div className="glass-card rounded-2xl p-4 border border-cyan-neon/20 space-y-4">
      {hasAI && (
        <div>
          <div className="flex items-center gap-2 mb-3">
            <Sparkles className="w-4 h-4 text-cyan-neon" />
            <h3 className="font-orbitron text-xs text-cyan-neon">AI SUGGESTIONS</h3>
          </div>
          <div className="space-y-2">
            {aiSuggestions.map((suggestion, i) => (
              <button
                key={i}
                onClick={() => onSelectSuggestion(suggestion.startTimestamp, suggestion.endTimestamp, suggestion.title)}
                className="w-full text-left p-3 rounded-xl bg-cyan-neon/5 border border-cyan-neon/10 hover:border-cyan-neon/40 transition-smooth"
              >
                <div className="flex items-center justify-between gap-2">
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-semibold text-foreground truncate">{suggestion.title}</p>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      {formatTime(suggestion.startTimestamp)} – {formatTime(suggestion.endTimestamp)}
                    </p>
                  </div>
                  <ViralScoreBadge score={Math.round(suggestion.viralScore)} />
                </div>
              </button>
            ))}
          </div>
        </div>
      )}

      {hasTrending && (
        <div>
          <div className="flex items-center gap-2 mb-3">
            <TrendingUp className="w-4 h-4 text-cyan-neon" />
            <h3 className="font-orbitron text-xs text-cyan-neon">TRENDING CLIPS</h3>
          </div>
          <div className="space-y-2">
            {trendingClips.slice(0, 5).map((clip) => (
              <button
                key={clip.id}
                onClick={() => onSelectSuggestion(clip.startTime, clip.endTime, clip.title)}
                className="w-full text-left p-3 rounded-xl bg-cyan-neon/5 border border-cyan-neon/10 hover:border-cyan-neon/40 transition-smooth"
              >
                <div className="flex items-center justify-between gap-2">
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-semibold text-foreground truncate">{clip.title}</p>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      {formatTime(clip.startTime)} – {formatTime(clip.endTime)}
                    </p>
                  </div>
                  <ViralScoreBadge score={Math.round(clip.score)} />
                </div>
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
