import React, { useState } from 'react';
import { useYouTubeValidation } from '../hooks/useYouTubeValidation';
import { useAutoGenerateClips } from '../hooks/useAutoGenerateClips';
import { Link, Sparkles, Loader2 } from 'lucide-react';
import type { AutoGeneratedClipSuggestion } from '../types/app';

interface VideoUrlFormProps {
  onVideoLoaded: (videoId: string, videoUrl: string) => void;
  onSuggestionsGenerated?: (suggestions: AutoGeneratedClipSuggestion[]) => void;
}

export default function VideoUrlForm({ onVideoLoaded, onSuggestionsGenerated }: VideoUrlFormProps) {
  const [url, setUrl] = useState('');
  const [error, setError] = useState('');
  const { extractVideoId } = useYouTubeValidation();
  const { mutate: generateClips, isPending: isGenerating } = useAutoGenerateClips();

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    const videoId = extractVideoId(url.trim());
    if (!videoId) {
      setError('Please enter a valid YouTube URL');
      return;
    }

    onVideoLoaded(videoId, url.trim());
  };

  const handleAutoGenerate = () => {
    const videoId = extractVideoId(url.trim());
    if (!videoId) return;

    generateClips(videoId, {
      onSuccess: (suggestions) => {
        onSuggestionsGenerated?.(suggestions);
      },
    });
  };

  const videoId = extractVideoId(url.trim());

  return (
    <div className="glass-card rounded-2xl p-4 border border-cyan-neon/20">
      <form onSubmit={handleSubmit} className="space-y-3">
        <div className="flex gap-2">
          <div className="relative flex-1">
            <Link className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <input
              type="url"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              placeholder="Paste YouTube URL..."
              className="w-full pl-9 pr-3 py-2 rounded-lg bg-purple-deep/50 border border-cyan-neon/20 text-foreground text-sm placeholder:text-muted-foreground focus:outline-none focus:border-cyan-neon transition-smooth"
            />
          </div>
          <button
            type="submit"
            disabled={!url.trim()}
            className="px-4 py-2 rounded-lg cyberpunk-btn transition-smooth text-sm font-semibold disabled:opacity-50"
          >
            Load
          </button>
        </div>

        {error && <p className="text-xs text-red-400">{error}</p>}

        {videoId && (
          <button
            type="button"
            onClick={handleAutoGenerate}
            disabled={isGenerating}
            className="w-full flex items-center justify-center gap-2 py-2 rounded-lg bg-cyan-neon/10 border border-cyan-neon/30 text-cyan-neon text-sm hover:bg-cyan-neon/20 transition-smooth disabled:opacity-50"
          >
            {isGenerating ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Sparkles className="w-4 h-4" />
            )}
            {isGenerating ? 'Generating AI Clips...' : 'Auto-Generate Clips with AI'}
          </button>
        )}
      </form>
    </div>
  );
}
