import { useMutation } from '@tanstack/react-query';
import type { AutoGeneratedClipSuggestion } from '../types/app';

const MOCK_SUGGESTIONS: AutoGeneratedClipSuggestion[] = [
  { startTimestamp: 30, endTimestamp: 60, title: 'Epic Clutch Moment', viralScore: 92 },
  { startTimestamp: 120, endTimestamp: 150, title: 'Insane Kill Streak', viralScore: 87 },
  { startTimestamp: 200, endTimestamp: 230, title: 'Victory Royale Highlight', viralScore: 78 },
  { startTimestamp: 300, endTimestamp: 330, title: 'Best Play of the Game', viralScore: 85 },
];

export function useAutoGenerateClips() {
  return useMutation({
    mutationFn: async (videoId: string): Promise<AutoGeneratedClipSuggestion[]> => {
      // Simulate AI generation delay
      await new Promise((r) => setTimeout(r, 1500));
      return MOCK_SUGGESTIONS;
    },
  });
}
