import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useActor } from './useActor';
import type { AutoGeneratedClipSuggestion } from '../backend';

// Mock AI-powered clip generation
// In production, this would call an AI service (OpenAI, Anthropic, etc.)
// through a secure backend endpoint to analyze video content
function generateMockAIClips(videoId: string): AutoGeneratedClipSuggestion[] {
  // Simulate AI analysis with realistic clip suggestions
  const suggestions: AutoGeneratedClipSuggestion[] = [
    {
      title: 'Epic Opening Moment',
      startTimestamp: BigInt(15),
      endTimestamp: BigInt(45),
      viralScore: 92,
    },
    {
      title: 'Insane Reaction Highlight',
      startTimestamp: BigInt(120),
      endTimestamp: BigInt(155),
      viralScore: 88,
    },
    {
      title: 'Best Part - Must Watch!',
      startTimestamp: BigInt(240),
      endTimestamp: BigInt(270),
      viralScore: 85,
    },
    {
      title: 'Crazy Unexpected Twist',
      startTimestamp: BigInt(360),
      endTimestamp: BigInt(395),
      viralScore: 81,
    },
  ];

  return suggestions;
}

export function useAutoGenerateClips() {
  const { actor } = useActor();
  const queryClient = useQueryClient();

  const mutation = useMutation({
    mutationFn: async (videoId: string) => {
      if (!actor) {
        throw new Error('Actor not initialized');
      }

      // Call backend method (currently returns empty array)
      // In the future, this could be enhanced to call a real AI service
      const backendSuggestions = await actor.generateClipsAutomatically(videoId);

      // If backend returns suggestions, use them; otherwise use mock AI
      if (backendSuggestions && backendSuggestions.length > 0) {
        return backendSuggestions;
      }

      // Generate AI-powered suggestions
      // TODO: Replace with actual AI API call through secure backend
      return generateMockAIClips(videoId);
    },
    onSuccess: () => {
      // Invalidate queries to refresh UI
      queryClient.invalidateQueries({ queryKey: ['clips'] });
      queryClient.invalidateQueries({ queryKey: ['trendingClips'] });
    },
  });

  return {
    generateClips: mutation.mutateAsync,
    isGenerating: mutation.isPending,
    isError: mutation.isError,
    error: mutation.error,
    data: mutation.data,
  };
}
