// Local type definitions for app-specific data structures
// These are not part of the backend interface

export type UserStatus = 'active' | 'inactive' | 'banned' | 'suspended';
export type SystemStatus = 'running' | 'restarting' | 'shutting_down' | 'paused';
export type SubmissionType = 'FeatureRequest' | 'BugReport';

export interface UserProfile {
  name: string;
  role: string;
  status: UserStatus;
  youtubeAuth?: YouTubeChannelAuth | null;
  googleOAuthCredentials?: GoogleOAuthCredentials | null;
  profilePicture?: any;
}

export interface YouTubeChannelAuth {
  accessToken: string;
  refreshToken: string;
  channelId: string;
  channelName: string;
  expiresAt: bigint;
}

export interface GoogleOAuthCredentials {
  accessToken: string;
  refreshToken: string;
  expiresAt: bigint;
  tokenType: string;
  idToken: string;
  scope: string;
}

export interface VideoClip {
  id: string;
  title: string;
  videoUrl: string;
  thumbnailUrl: string;
  startTime: number;
  endTime: number;
  createdAt: bigint;
  score: number;
}

export interface TrendingClipAnalytics {
  id: string;
  title: string;
  scoreMetrics: number;
  trendingScore: number;
}

export interface AutoGeneratedClipSuggestion {
  startTimestamp: number;
  endTimestamp: number;
  title: string;
  viralScore: number;
}

export interface FeedbackSubmission {
  id: bigint;
  submitterPrincipal: string;
  submitterUserId: string;
  submissionType: SubmissionType;
  title: string;
  description: string;
  timestamp: number;
}

export interface ScheduledUpload {
  id: string;
  clipId: string;
  scheduledAt: bigint;
  createdAt: bigint;
}

export interface ContentEntry {
  id: string;
  title: string;
  body: string;
  createdAt: bigint;
  updatedAt: bigint;
}

export interface ActivityLog {
  id: string;
  userPrincipal: string;
  action: string;
  timestamp: bigint;
}

export interface AdminMessage {
  id: string;
  fromPrincipal: string;
  toPrincipal: string;
  fromUserId: string;
  toUserId: string;
  body: string;
  sentAt: bigint;
}

export interface ClipMetadata {
  videoId: string;
  startTimestamp: number;
  endTimestamp: number;
  title: string;
}
