import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Clock, Loader2, Sparkles, TrendingUp } from "lucide-react";
import type { AutoGeneratedClipSuggestion } from "../backend";
import { useTrendingClips } from "../hooks/useTrendingClips";
import ViralScoreBadge from "./ViralScoreBadge";

interface ClipSuggestionsProps {
  onSelectSuggestion: (
    startTime: number,
    endTime: number,
    title: string,
  ) => void;
  aiSuggestions?: AutoGeneratedClipSuggestion[];
}

export default function ClipSuggestions({
  onSelectSuggestion,
  aiSuggestions = [],
}: ClipSuggestionsProps) {
  const { data: trendingClips, isLoading } = useTrendingClips();

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, "0")}`;
  };

  // Show AI suggestions if available, otherwise show trending clips
  const hasAISuggestions = aiSuggestions.length > 0;

  return (
    <Card className="h-full">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          {hasAISuggestions ? (
            <>
              <Sparkles className="w-5 h-5 text-primary" />
              AI-Generated Clips
            </>
          ) : (
            <>
              <TrendingUp className="w-5 h-5 text-primary" />
              Viral Clip Suggestions
            </>
          )}
        </CardTitle>
        <CardDescription>
          {hasAISuggestions
            ? "AI-powered clip suggestions for this video"
            : "Top clips ranked by viral potential"}
        </CardDescription>
      </CardHeader>
      <CardContent>
        {isLoading && !hasAISuggestions ? (
          <div className="flex items-center justify-center py-8">
            <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
          </div>
        ) : hasAISuggestions ? (
          <ScrollArea className="h-[400px] pr-4">
            <div className="space-y-3">
              {aiSuggestions.map((suggestion, _index) => {
                const startTime = Number(suggestion.startTimestamp);
                const endTime = Number(suggestion.endTimestamp);
                const duration = endTime - startTime;

                return (
                  <div
                    key={`suggestion-${suggestion.startTimestamp}-${suggestion.endTimestamp}`}
                    className="border rounded-lg p-3 space-y-2 hover:bg-muted/50 transition-colors bg-primary/5"
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1">
                          <Sparkles className="w-3 h-3 text-primary" />
                          <h4 className="font-medium text-sm line-clamp-2">
                            {suggestion.title}
                          </h4>
                        </div>
                        <div className="flex items-center gap-2 text-xs text-muted-foreground">
                          <Clock className="w-3 h-3" />
                          <span>
                            {formatTime(startTime)} - {formatTime(endTime)}
                          </span>
                          <span>({duration}s)</span>
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center justify-between gap-2">
                      <ViralScoreBadge
                        score={Math.round(suggestion.viralScore)}
                        showLabel={false}
                        size="sm"
                      />
                      <Button
                        size="sm"
                        variant="default"
                        onClick={() =>
                          onSelectSuggestion(
                            startTime,
                            endTime,
                            suggestion.title,
                          )
                        }
                        className="text-xs"
                      >
                        Use This Clip
                      </Button>
                    </div>
                  </div>
                );
              })}
            </div>
          </ScrollArea>
        ) : !trendingClips || trendingClips.length === 0 ? (
          <div className="text-center py-8 text-muted-foreground">
            <Sparkles className="w-12 h-12 mx-auto mb-3 opacity-50" />
            <p className="text-sm">No suggestions yet</p>
            <p className="text-xs mt-1">
              Create some clips or use AI generation
            </p>
          </div>
        ) : (
          <ScrollArea className="h-[400px] pr-4">
            <div className="space-y-3">
              {trendingClips.map((clip) => {
                const startTime = Number(clip.startTime);
                const endTime = Number(clip.endTime);
                const duration = endTime - startTime;

                return (
                  <div
                    key={clip.id}
                    className="border rounded-lg p-3 space-y-2 hover:bg-muted/50 transition-colors"
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex-1 min-w-0">
                        <h4 className="font-medium text-sm line-clamp-2 mb-1">
                          {clip.title}
                        </h4>
                        <div className="flex items-center gap-2 text-xs text-muted-foreground">
                          <Clock className="w-3 h-3" />
                          <span>
                            {formatTime(startTime)} - {formatTime(endTime)}
                          </span>
                          <span>({duration}s)</span>
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center justify-between gap-2">
                      <ViralScoreBadge
                        score={Math.round(clip.score)}
                        showLabel={false}
                        size="sm"
                      />
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() =>
                          onSelectSuggestion(startTime, endTime, clip.title)
                        }
                        className="text-xs"
                      >
                        Use This Clip
                      </Button>
                    </div>
                  </div>
                );
              })}
            </div>
          </ScrollArea>
        )}
      </CardContent>
    </Card>
  );
}
