import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Clock, Loader2, Sparkles, TrendingUp, Zap } from "lucide-react";
import { useState } from "react";
import type { AutoGeneratedClipSuggestion } from "../backend";
import { useTrendingClips } from "../hooks/useTrendingClips";
import ViralScoreBadge from "./ViralScoreBadge";

interface ClipSuggestionsProps {
  onSelectSuggestion: (
    startTime: number,
    endTime: number,
    title: string,
  ) => void;
  aiSuggestions?: AutoGeneratedClipSuggestion[];
}

interface HypeMoment {
  title: string;
  startTime: number;
  endTime: number;
  score: number;
  type: "peak" | "hype" | "victory";
}

const FAKE_HYPE_MOMENTS: HypeMoment[] = [
  {
    title: "🔥 Hype Moment at 0:45",
    startTime: 45,
    endTime: 72,
    score: 94,
    type: "hype",
  },
  {
    title: "⚡ Peak Action at 1:20",
    startTime: 80,
    endTime: 105,
    score: 88,
    type: "peak",
  },
  {
    title: "🏆 Victory Sequence at 2:10",
    startTime: 130,
    endTime: 158,
    score: 97,
    type: "victory",
  },
  {
    title: "🎯 Clutch Play at 3:05",
    startTime: 185,
    endTime: 210,
    score: 91,
    type: "hype",
  },
];

export default function ClipSuggestions({
  onSelectSuggestion,
  aiSuggestions = [],
}: ClipSuggestionsProps) {
  const { data: trendingClips, isLoading } = useTrendingClips();
  const [isDetecting, setIsDetecting] = useState(false);
  const [hypeMoments, setHypeMoments] = useState<HypeMoment[]>([]);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, "0")}`;
  };

  const handleDetectHype = async () => {
    setIsDetecting(true);
    setHypeMoments([]);
    await new Promise((r) => setTimeout(r, 2000));
    setHypeMoments(FAKE_HYPE_MOMENTS);
    setIsDetecting(false);
  };

  // Show AI suggestions if available, otherwise show trending clips
  const hasAISuggestions = aiSuggestions.length > 0;
  const hasHypeMoments = hypeMoments.length > 0;

  return (
    <Card className="h-full">
      <CardHeader>
        <div className="flex items-center justify-between gap-2">
          <div className="flex-1">
            <CardTitle className="flex items-center gap-2">
              {hasAISuggestions ? (
                <>
                  <Sparkles className="w-5 h-5 text-primary" />
                  AI-Generated Clips
                </>
              ) : (
                <>
                  <TrendingUp className="w-5 h-5 text-primary" />
                  Viral Clip Suggestions
                </>
              )}
            </CardTitle>
            <CardDescription>
              {hasAISuggestions
                ? "AI-powered clip suggestions for this video"
                : "Top clips ranked by viral potential"}
            </CardDescription>
          </div>
          {/* Detect Hype Button */}
          <Button
            size="sm"
            variant="outline"
            onClick={handleDetectHype}
            disabled={isDetecting}
            className="shrink-0 border-yellow-500/30 text-yellow-300 hover:bg-yellow-500/10 text-xs h-8 gap-1.5"
            data-ocid="suggestions.button"
          >
            {isDetecting ? (
              <>
                <Loader2 className="w-3 h-3 animate-spin" />
                Scanning…
              </>
            ) : (
              <>
                <Zap className="w-3 h-3" />
                Detect Hype
              </>
            )}
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        {/* Hype detection animation */}
        {isDetecting && (
          <div className="flex flex-col items-center justify-center py-6 gap-3 mb-3 rounded-xl bg-yellow-500/5 border border-yellow-500/20">
            <div className="flex items-end gap-0.5 h-8">
              {[3, 7, 5, 9, 4, 8, 6, 10, 5, 7].map((h, i) => (
                <div
                  // biome-ignore lint/suspicious/noArrayIndexKey: static decorative bars
                  key={i}
                  className="w-1.5 rounded-sm bg-yellow-400"
                  style={{
                    height: `${h * 3}px`,
                    animation: `waveform-pulse ${0.4 + i * 0.05}s ease-in-out infinite`,
                    animationDelay: `${i * 0.07}s`,
                  }}
                />
              ))}
            </div>
            <p className="text-yellow-300 text-xs font-medium">
              Scanning audio for hype peaks…
            </p>
          </div>
        )}

        {/* Hype moments */}
        {hasHypeMoments && (
          <div className="mb-4">
            <div className="flex items-center gap-2 mb-2">
              <Zap className="w-3.5 h-3.5 text-yellow-400" />
              <span className="text-yellow-300 text-xs font-semibold">
                Hype Moments Detected
              </span>
            </div>
            <div className="space-y-2">
              {hypeMoments.map((moment, idx) => (
                <div
                  key={moment.startTime}
                  className="border border-yellow-500/20 rounded-lg p-3 space-y-2 bg-yellow-500/5 hover:bg-yellow-500/10 transition-colors cursor-pointer"
                  data-ocid={`suggestions.item.${idx + 1}`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex-1 min-w-0">
                      <h4 className="font-medium text-sm text-yellow-200 line-clamp-1">
                        {moment.title}
                      </h4>
                      <div className="flex items-center gap-2 text-xs text-muted-foreground mt-0.5">
                        <Clock className="w-3 h-3" />
                        <span>
                          {formatTime(moment.startTime)} –{" "}
                          {formatTime(moment.endTime)}
                        </span>
                        <span>({moment.endTime - moment.startTime}s)</span>
                      </div>
                    </div>
                    <ViralScoreBadge
                      score={moment.score}
                      showLabel={false}
                      size="sm"
                    />
                  </div>
                  <Button
                    size="sm"
                    onClick={() =>
                      onSelectSuggestion(
                        moment.startTime,
                        moment.endTime,
                        moment.title,
                      )
                    }
                    className="w-full text-xs h-7 bg-yellow-500/20 hover:bg-yellow-500/30 text-yellow-200 border border-yellow-500/30"
                  >
                    Use This Clip
                  </Button>
                </div>
              ))}
            </div>
          </div>
        )}

        {isLoading && !hasAISuggestions ? (
          <div className="flex items-center justify-center py-8">
            <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
          </div>
        ) : hasAISuggestions ? (
          <ScrollArea className="h-[300px] pr-4">
            <div className="space-y-3">
              {aiSuggestions.map((suggestion, _index) => {
                const startTime = Number(suggestion.startTimestamp);
                const endTime = Number(suggestion.endTimestamp);
                const duration = endTime - startTime;

                return (
                  <div
                    key={`suggestion-${suggestion.startTimestamp}-${suggestion.endTimestamp}`}
                    className="border rounded-lg p-3 space-y-2 hover:bg-muted/50 transition-colors bg-primary/5 border-primary/20"
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1">
                          <Sparkles className="w-3 h-3 text-primary" />
                          <h4 className="font-medium text-sm line-clamp-2">
                            {suggestion.title}
                          </h4>
                        </div>
                        <div className="flex items-center gap-2 text-xs text-muted-foreground">
                          <Clock className="w-3 h-3" />
                          <span>
                            {formatTime(startTime)} - {formatTime(endTime)}
                          </span>
                          <span>({duration}s)</span>
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center justify-between gap-2">
                      <ViralScoreBadge
                        score={Math.round(suggestion.viralScore)}
                        showLabel={false}
                        size="sm"
                      />
                      <Button
                        size="sm"
                        variant="default"
                        onClick={() =>
                          onSelectSuggestion(
                            startTime,
                            endTime,
                            suggestion.title,
                          )
                        }
                        className="text-xs"
                      >
                        Use This Clip
                      </Button>
                    </div>
                  </div>
                );
              })}
            </div>
          </ScrollArea>
        ) : !trendingClips || trendingClips.length === 0 ? (
          <div
            className="text-center py-8 text-muted-foreground"
            data-ocid="suggestions.empty_state"
          >
            <Sparkles className="w-12 h-12 mx-auto mb-3 opacity-50" />
            <p className="text-sm">No suggestions yet</p>
            <p className="text-xs mt-1">
              Create some clips or use AI generation
            </p>
          </div>
        ) : (
          <ScrollArea className="h-[300px] pr-4">
            <div className="space-y-3">
              {trendingClips.map((clip) => {
                const startTime = Number(clip.startTime);
                const endTime = Number(clip.endTime);
                const duration = endTime - startTime;

                return (
                  <div
                    key={clip.id}
                    className="border rounded-lg p-3 space-y-2 hover:bg-muted/50 transition-colors border-border"
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex-1 min-w-0">
                        <h4 className="font-medium text-sm line-clamp-2 mb-1">
                          {clip.title}
                        </h4>
                        <div className="flex items-center gap-2 text-xs text-muted-foreground">
                          <Clock className="w-3 h-3" />
                          <span>
                            {formatTime(startTime)} - {formatTime(endTime)}
                          </span>
                          <span>({duration}s)</span>
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center justify-between gap-2">
                      <ViralScoreBadge
                        score={Math.round(clip.score)}
                        showLabel={false}
                        size="sm"
                      />
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() =>
                          onSelectSuggestion(startTime, endTime, clip.title)
                        }
                        className="text-xs"
                      >
                        Use This Clip
                      </Button>
                    </div>
                  </div>
                );
              })}
            </div>
          </ScrollArea>
        )}
      </CardContent>
    </Card>
  );
}
