import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { AlertCircle, Link2, Loader2, Sparkles } from "lucide-react";
import { useState } from "react";
import type { AutoGeneratedClipSuggestion } from "../backend";
import { useAutoGenerateClips } from "../hooks/useAutoGenerateClips";
import { useYouTubeValidation } from "../hooks/useYouTubeValidation";

interface VideoUrlFormProps {
  onSubmit: (url: string, videoId: string) => void;
  onClipsGenerated?: (clips: AutoGeneratedClipSuggestion[]) => void;
}

export default function VideoUrlForm({
  onSubmit,
  onClipsGenerated,
}: VideoUrlFormProps) {
  const [url, setUrl] = useState("");
  const [currentVideoId, setCurrentVideoId] = useState<string>("");
  const { validateUrl, extractVideoId } = useYouTubeValidation();
  const { generateClips, isGenerating, isError, error } =
    useAutoGenerateClips();
  const [validationError, setValidationError] = useState<string>("");

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setValidationError("");

    if (!url.trim()) {
      setValidationError("Please enter a YouTube URL");
      return;
    }

    if (!validateUrl(url)) {
      setValidationError(
        "Invalid YouTube URL. Please use a valid youtube.com or youtu.be link",
      );
      return;
    }

    const videoId = extractVideoId(url);
    if (!videoId) {
      setValidationError("Could not extract video ID from URL");
      return;
    }

    setCurrentVideoId(videoId);
    onSubmit(url, videoId);
  };

  const handleGenerateAIClips = async () => {
    if (!currentVideoId) {
      setValidationError("Please load a video first");
      return;
    }

    try {
      const clips = await generateClips(currentVideoId);
      if (onClipsGenerated && clips) {
        onClipsGenerated(clips);
      }
    } catch (err) {
      console.error("Failed to generate AI clips:", err);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Link2 className="w-5 h-5" />
          Enter YouTube Video URL
        </CardTitle>
        <CardDescription>
          Paste a YouTube video link to get started
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="flex gap-2">
            <Input
              type="text"
              placeholder="https://www.youtube.com/watch?v=..."
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              className="flex-1"
            />
            <Button type="submit">Load Video</Button>
          </div>

          {currentVideoId && (
            <div className="pt-2">
              <Button
                type="button"
                variant="secondary"
                className="w-full"
                onClick={handleGenerateAIClips}
                disabled={isGenerating}
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Generating AI Clips...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4 mr-2" />
                    Generate AI Clips
                  </>
                )}
              </Button>
            </div>
          )}

          {validationError && (
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>{validationError}</AlertDescription>
            </Alert>
          )}

          {isError && error && (
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>
                Failed to generate AI clips:{" "}
                {error instanceof Error ? error.message : "Unknown error"}
              </AlertDescription>
            </Alert>
          )}
        </form>
      </CardContent>
    </Card>
  );
}
