/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AutoGeneratedClipSuggestion {
  'title' : string,
  'viralScore' : number,
  'endTimestamp' : bigint,
  'startTimestamp' : bigint,
}
export interface Clip {
  'id' : string,
  'startTime' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'endTime' : bigint,
  'createdAt' : Time,
  'score' : number,
  'videoUrl' : string,
}
export type Time = bigint;
export interface TrendingClipAnalytics {
  'id' : string,
  'title' : string,
  'scoreMetrics' : number,
  'trendingScore' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteClip' : ActorMethod<[string], undefined>,
  'findRelatedClips' : ActorMethod<[string], Array<string>>,
  'generateClipsAutomatically' : ActorMethod<
    [string],
    Array<AutoGeneratedClipSuggestion>
  >,
  'getAllClips' : ActorMethod<[], Array<Clip>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClipById' : ActorMethod<[string], Clip>,
  'getTotalClipsCount' : ActorMethod<[], bigint>,
  'getTrendingClips' : ActorMethod<[], Array<Clip>>,
  'getTrendingClipsAnalytics' : ActorMethod<[], Array<TrendingClipAnalytics>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveClip' : ActorMethod<
    [string, string, string, bigint, bigint, number],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];