/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AutoGeneratedClipSuggestion {
  'title' : string,
  'viralScore' : number,
  'endTimestamp' : bigint,
  'startTimestamp' : bigint,
}
export interface ClipMetadata {
  'title' : string,
  'endTimestamp' : bigint,
  'startTimestamp' : bigint,
  'videoId' : string,
}
export interface GoogleOAuthCredentials {
  'expiresAt' : Time,
  'refreshToken' : string,
  'scope' : string,
  'accessToken' : string,
  'idToken' : string,
  'tokenType' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TrendingClipAnalytics {
  'id' : string,
  'title' : string,
  'scoreMetrics' : number,
  'trendingScore' : number,
}
export interface UserProfile {
  'youtubeAuth' : [] | [YouTubeChannelAuth],
  'name' : string,
  'role' : UserRole,
  'googleOAuthCredentials' : [] | [GoogleOAuthCredentials],
}
export type UserRole = { 'admin' : null } |
  { 'owner' : null } |
  { 'user' : null } |
  { 'friend' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoClip {
  'id' : string,
  'startTime' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'endTime' : bigint,
  'createdAt' : Time,
  'score' : number,
  'videoUrl' : string,
}
export interface YouTubeChannelAuth {
  'channelName' : string,
  'expiresAt' : Time,
  'channelId' : string,
  'refreshToken' : string,
  'accessToken' : string,
}
export interface YouTubePostResult {
  'errorMessage' : string,
  'success' : boolean,
  'videoUrl' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdminByUserId' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'connectYouTubeChannel' : ActorMethod<
    [string, string, string, string, Time],
    undefined
  >,
  'deleteClip' : ActorMethod<[string], undefined>,
  'findRelatedClips' : ActorMethod<[string], Array<string>>,
  'generateClipsAutomatically' : ActorMethod<
    [string],
    Array<AutoGeneratedClipSuggestion>
  >,
  'generateDownloadVideoUrl' : ActorMethod<[string, bigint, bigint], string>,
  'getAdminsAsAdmin' : ActorMethod<[], Array<string>>,
  'getAllClips' : ActorMethod<[string], Array<VideoClip>>,
  'getAllUserRoles' : ActorMethod<[], Array<[Principal, UserRole]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getClipById' : ActorMethod<[string], VideoClip>,
  'getOwnRole' : ActorMethod<[], [] | [UserRole]>,
  'getTotalClipsCount' : ActorMethod<[], bigint>,
  'getTrendingClips' : ActorMethod<[], Array<VideoClip>>,
  'getTrendingClipsAnalytics' : ActorMethod<[], Array<TrendingClipAnalytics>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasGoogleOAuthCredentials' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isYouTubeChannelConnected' : ActorMethod<[], boolean>,
  'postClipToYouTube' : ActorMethod<[ClipMetadata], YouTubePostResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveClip' : ActorMethod<
    [string, string, string, bigint, bigint, number],
    string
  >,
  'setUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'storeGoogleOAuthCredentials' : ActorMethod<[string, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];