/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AutoGeneratedClipSuggestion = IDL.Record({
  'title' : IDL.Text,
  'viralScore' : IDL.Float64,
  'endTimestamp' : IDL.Nat,
  'startTimestamp' : IDL.Nat,
});
export const VideoClip = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'endTime' : IDL.Nat,
  'createdAt' : Time,
  'score' : IDL.Float64,
  'videoUrl' : IDL.Text,
});
export const YouTubeChannelAuth = IDL.Record({
  'channelName' : IDL.Text,
  'expiresAt' : Time,
  'channelId' : IDL.Text,
  'refreshToken' : IDL.Text,
  'accessToken' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'youtubeAuth' : IDL.Opt(YouTubeChannelAuth),
  'name' : IDL.Text,
});
export const TrendingClipAnalytics = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'scoreMetrics' : IDL.Float64,
  'trendingScore' : IDL.Float64,
});
export const ClipMetadata = IDL.Record({
  'title' : IDL.Text,
  'endTimestamp' : IDL.Nat,
  'startTimestamp' : IDL.Nat,
  'videoId' : IDL.Text,
});
export const YouTubePostResult = IDL.Record({
  'errorMessage' : IDL.Text,
  'success' : IDL.Bool,
  'videoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'connectYouTubeChannel' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
      [],
      [],
    ),
  'deleteClip' : IDL.Func([IDL.Text], [], []),
  'findRelatedClips' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'generateClipsAutomatically' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AutoGeneratedClipSuggestion)],
      ['query'],
    ),
  'getAllClips' : IDL.Func([IDL.Text], [IDL.Vec(VideoClip)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClipById' : IDL.Func([IDL.Text], [VideoClip], ['query']),
  'getTotalClipsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTrendingClips' : IDL.Func([], [IDL.Vec(VideoClip)], ['query']),
  'getTrendingClipsAnalytics' : IDL.Func(
      [],
      [IDL.Vec(TrendingClipAnalytics)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isYouTubeChannelConnected' : IDL.Func([], [IDL.Bool], ['query']),
  'postClipToYouTube' : IDL.Func([ClipMetadata], [YouTubePostResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveClip' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AutoGeneratedClipSuggestion = IDL.Record({
    'title' : IDL.Text,
    'viralScore' : IDL.Float64,
    'endTimestamp' : IDL.Nat,
    'startTimestamp' : IDL.Nat,
  });
  const VideoClip = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'endTime' : IDL.Nat,
    'createdAt' : Time,
    'score' : IDL.Float64,
    'videoUrl' : IDL.Text,
  });
  const YouTubeChannelAuth = IDL.Record({
    'channelName' : IDL.Text,
    'expiresAt' : Time,
    'channelId' : IDL.Text,
    'refreshToken' : IDL.Text,
    'accessToken' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'youtubeAuth' : IDL.Opt(YouTubeChannelAuth),
    'name' : IDL.Text,
  });
  const TrendingClipAnalytics = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'scoreMetrics' : IDL.Float64,
    'trendingScore' : IDL.Float64,
  });
  const ClipMetadata = IDL.Record({
    'title' : IDL.Text,
    'endTimestamp' : IDL.Nat,
    'startTimestamp' : IDL.Nat,
    'videoId' : IDL.Text,
  });
  const YouTubePostResult = IDL.Record({
    'errorMessage' : IDL.Text,
    'success' : IDL.Bool,
    'videoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'connectYouTubeChannel' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
        [],
        [],
      ),
    'deleteClip' : IDL.Func([IDL.Text], [], []),
    'findRelatedClips' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'generateClipsAutomatically' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AutoGeneratedClipSuggestion)],
        ['query'],
      ),
    'getAllClips' : IDL.Func([IDL.Text], [IDL.Vec(VideoClip)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClipById' : IDL.Func([IDL.Text], [VideoClip], ['query']),
    'getTotalClipsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTrendingClips' : IDL.Func([], [IDL.Vec(VideoClip)], ['query']),
    'getTrendingClipsAnalytics' : IDL.Func(
        [],
        [IDL.Vec(TrendingClipAnalytics)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isYouTubeChannelConnected' : IDL.Func([], [IDL.Bool], ['query']),
    'postClipToYouTube' : IDL.Func([ClipMetadata], [YouTubePostResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveClip' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };