/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Clip = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'endTime' : IDL.Nat,
  'createdAt' : Time,
  'videoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteClip' : IDL.Func([IDL.Text], [], []),
  'getAllClips' : IDL.Func([], [IDL.Vec(Clip)], ['query']),
  'getClipById' : IDL.Func([IDL.Text], [Clip], ['query']),
  'saveClip' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Clip = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'endTime' : IDL.Nat,
    'createdAt' : Time,
    'videoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteClip' : IDL.Func([IDL.Text], [], []),
    'getAllClips' : IDL.Func([], [IDL.Vec(Clip)], ['query']),
    'getClipById' : IDL.Func([IDL.Text], [Clip], ['query']),
    'saveClip' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };