/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AutoGeneratedClipSuggestion {
    title: string;
    viralScore: number;
    endTimestamp: bigint;
    startTimestamp: bigint;
}
export interface ClipMetadata {
    title: string;
    endTimestamp: bigint;
    startTimestamp: bigint;
    videoId: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface VideoClip {
    id: string;
    startTime: bigint;
    title: string;
    thumbnailUrl: string;
    endTime: bigint;
    createdAt: Time;
    score: number;
    videoUrl: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface TrendingClipAnalytics {
    id: string;
    title: string;
    scoreMetrics: number;
    trendingScore: number;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface FeedbackSubmission {
    id: bigint;
    title: string;
    submitterPrincipal: string;
    description: string;
    timestamp: bigint;
    submissionType: SubmissionType;
    submitterUserId: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface YouTubeChannelAuth {
    channelName: string;
    expiresAt: Time;
    channelId: string;
    refreshToken: string;
    accessToken: string;
}
export interface YouTubePostResult {
    errorMessage: string;
    success: boolean;
    videoUrl: string;
}
export interface GoogleOAuthCredentials {
    expiresAt: Time;
    refreshToken: string;
    scope: string;
    accessToken: string;
    idToken: string;
    tokenType: string;
}
export interface UserProfile {
    status: UserStatus;
    youtubeAuth?: YouTubeChannelAuth;
    name: string;
    role: UserRole;
    googleOAuthCredentials?: GoogleOAuthCredentials;
}
export enum SubmissionType {
    BugReport = "BugReport",
    FeatureRequest = "FeatureRequest"
}
export enum UserRole {
    admin = "admin",
    owner = "owner",
    user = "user",
    friend = "friend"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserStatus {
    active = "active",
    banned = "banned",
    inactive = "inactive",
    suspended = "suspended"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAdminByUserId(userId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    connectYouTubeChannel(accessToken: string, refreshToken: string, channelId: string, channelName: string, expiresAt: Time): Promise<void>;
    deleteClip(clipId: string): Promise<void>;
    deleteFeedbackSubmission(id: bigint): Promise<void>;
    findRelatedClips(clipId: string): Promise<Array<string>>;
    generateClipsAutomatically(_youtubeVideoId: string): Promise<Array<AutoGeneratedClipSuggestion>>;
    generateDownloadVideoUrl(videoId: string, startTime: bigint, endTime: bigint): Promise<string>;
    getAdminsAsAdmin(): Promise<Array<string>>;
    getAllClips(_searchText: string): Promise<Array<VideoClip>>;
    getAllUserRoles(): Promise<Array<[Principal, UserRole]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getClipById(clipId: string): Promise<VideoClip>;
    getFeedbackSubmissions(): Promise<Array<FeedbackSubmission>>;
    getOwnRole(): Promise<UserRole | null>;
    getTotalClipsCount(): Promise<bigint>;
    getTrendingClips(): Promise<Array<VideoClip>>;
    getTrendingClipsAnalytics(): Promise<Array<TrendingClipAnalytics>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasGoogleOAuthCredentials(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isYouTubeChannelConnected(): Promise<boolean>;
    postClipToYouTube(clipMetadata: ClipMetadata): Promise<YouTubePostResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveClip(title: string, videoUrl: string, thumbnailUrl: string, startTime: bigint, endTime: bigint, score: number): Promise<string>;
    setUserRole(target: Principal, userRole: UserRole): Promise<void>;
    storeGoogleOAuthCredentials(authorizationCode: string, redirectUri: string): Promise<void>;
    submitFeedback(submissionType: SubmissionType, title: string, description: string): Promise<bigint>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateUserStatus(target: Principal, newStatus: UserStatus): Promise<void>;
}
import type { FeedbackSubmission as _FeedbackSubmission, GoogleOAuthCredentials as _GoogleOAuthCredentials, SubmissionType as _SubmissionType, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, UserStatus as _UserStatus, YouTubeChannelAuth as _YouTubeChannelAuth } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdminByUserId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminByUserId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminByUserId(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async connectYouTubeChannel(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.connectYouTubeChannel(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.connectYouTubeChannel(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteClip(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClip(arg0);
            return result;
        }
    }
    async deleteFeedbackSubmission(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeedbackSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeedbackSubmission(arg0);
            return result;
        }
    }
    async findRelatedClips(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.findRelatedClips(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findRelatedClips(arg0);
            return result;
        }
    }
    async generateClipsAutomatically(arg0: string): Promise<Array<AutoGeneratedClipSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateClipsAutomatically(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateClipsAutomatically(arg0);
            return result;
        }
    }
    async generateDownloadVideoUrl(arg0: string, arg1: bigint, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateDownloadVideoUrl(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateDownloadVideoUrl(arg0, arg1, arg2);
            return result;
        }
    }
    async getAdminsAsAdmin(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminsAsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminsAsAdmin();
            return result;
        }
    }
    async getAllClips(arg0: string): Promise<Array<VideoClip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClips(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClips(arg0);
            return result;
        }
    }
    async getAllUserRoles(): Promise<Array<[Principal, UserRole]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserRoles();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserRoles();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClipById(arg0: string): Promise<VideoClip> {
        if (this.processError) {
            try {
                const result = await this.actor.getClipById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClipById(arg0);
            return result;
        }
    }
    async getFeedbackSubmissions(): Promise<Array<FeedbackSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbackSubmissions();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbackSubmissions();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnRole(): Promise<UserRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnRole();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnRole();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalClipsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalClipsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalClipsCount();
            return result;
        }
    }
    async getTrendingClips(): Promise<Array<VideoClip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingClips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingClips();
            return result;
        }
    }
    async getTrendingClipsAnalytics(): Promise<Array<TrendingClipAnalytics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingClipsAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingClipsAnalytics();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasGoogleOAuthCredentials(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasGoogleOAuthCredentials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasGoogleOAuthCredentials();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isYouTubeChannelConnected(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isYouTubeChannelConnected();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isYouTubeChannelConnected();
            return result;
        }
    }
    async postClipToYouTube(arg0: ClipMetadata): Promise<YouTubePostResult> {
        if (this.processError) {
            try {
                const result = await this.actor.postClipToYouTube(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postClipToYouTube(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveClip(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: number): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveClip(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveClip(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async setUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async storeGoogleOAuthCredentials(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeGoogleOAuthCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeGoogleOAuthCredentials(arg0, arg1);
            return result;
        }
    }
    async submitFeedback(arg0: SubmissionType, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(to_candid_SubmissionType_n28(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(to_candid_SubmissionType_n28(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateUserStatus(arg0: Principal, arg1: UserStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserStatus(arg0, to_candid_UserStatus_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserStatus(arg0, to_candid_UserStatus_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_FeedbackSubmission_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedbackSubmission): FeedbackSubmission {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionType): SubmissionType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_YouTubeChannelAuth]): YouTubeChannelAuth | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GoogleOAuthCredentials]): GoogleOAuthCredentials | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRole]): UserRole | null {
    return value.length === 0 ? null : from_candid_UserRole_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    submitterPrincipal: string;
    description: string;
    timestamp: bigint;
    submissionType: _SubmissionType;
    submitterUserId: string;
}): {
    id: bigint;
    title: string;
    submitterPrincipal: string;
    description: string;
    timestamp: bigint;
    submissionType: SubmissionType;
    submitterUserId: string;
} {
    return {
        id: value.id,
        title: value.title,
        submitterPrincipal: value.submitterPrincipal,
        description: value.description,
        timestamp: value.timestamp,
        submissionType: from_candid_SubmissionType_n19(_uploadFile, _downloadFile, value.submissionType),
        submitterUserId: value.submitterUserId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _UserStatus;
    youtubeAuth: [] | [_YouTubeChannelAuth];
    name: string;
    role: _UserRole;
    googleOAuthCredentials: [] | [_GoogleOAuthCredentials];
}): {
    status: UserStatus;
    youtubeAuth?: YouTubeChannelAuth;
    name: string;
    role: UserRole;
    googleOAuthCredentials?: GoogleOAuthCredentials;
} {
    return {
        status: from_candid_UserStatus_n10(_uploadFile, _downloadFile, value.status),
        youtubeAuth: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.youtubeAuth)),
        name: value.name,
        role: from_candid_UserRole_n5(_uploadFile, _downloadFile, value.role),
        googleOAuthCredentials: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.googleOAuthCredentials))
    };
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserRole]): [Principal, UserRole] {
    return [
        value[0],
        from_candid_UserRole_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    banned: null;
} | {
    inactive: null;
} | {
    suspended: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "banned" in value ? UserStatus.banned : "inactive" in value ? UserStatus.inactive : "suspended" in value ? UserStatus.suspended : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BugReport: null;
} | {
    FeatureRequest: null;
}): SubmissionType {
    return "BugReport" in value ? SubmissionType.BugReport : "FeatureRequest" in value ? SubmissionType.FeatureRequest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    owner: null;
} | {
    user: null;
} | {
    friend: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "owner" in value ? UserRole.owner : "user" in value ? UserRole.user : "friend" in value ? UserRole.friend : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeedbackSubmission>): Array<FeedbackSubmission> {
    return value.map((x)=>from_candid_FeedbackSubmission_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserRole]>): Array<[Principal, UserRole]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function to_candid_SubmissionType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionType): _SubmissionType {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): _UserStatus {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: UserStatus;
    youtubeAuth?: YouTubeChannelAuth;
    name: string;
    role: UserRole;
    googleOAuthCredentials?: GoogleOAuthCredentials;
}): {
    status: _UserStatus;
    youtubeAuth: [] | [_YouTubeChannelAuth];
    name: string;
    role: _UserRole;
    googleOAuthCredentials: [] | [_GoogleOAuthCredentials];
} {
    return {
        status: to_candid_UserStatus_n24(_uploadFile, _downloadFile, value.status),
        youtubeAuth: value.youtubeAuth ? candid_some(value.youtubeAuth) : candid_none(),
        name: value.name,
        role: to_candid_UserRole_n26(_uploadFile, _downloadFile, value.role),
        googleOAuthCredentials: value.googleOAuthCredentials ? candid_some(value.googleOAuthCredentials) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): {
    active: null;
} | {
    banned: null;
} | {
    inactive: null;
} | {
    suspended: null;
} {
    return value == UserStatus.active ? {
        active: null
    } : value == UserStatus.banned ? {
        banned: null
    } : value == UserStatus.inactive ? {
        inactive: null
    } : value == UserStatus.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    owner: null;
} | {
    user: null;
} | {
    friend: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.owner ? {
        owner: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.friend ? {
        friend: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionType): {
    BugReport: null;
} | {
    FeatureRequest: null;
} {
    return value == SubmissionType.BugReport ? {
        BugReport: null
    } : value == SubmissionType.FeatureRequest ? {
        FeatureRequest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
