/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AutoGeneratedClipSuggestion = IDL.Record({
  'title' : IDL.Text,
  'viralScore' : IDL.Float64,
  'endTimestamp' : IDL.Nat,
  'startTimestamp' : IDL.Nat,
});
export const VideoClip = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'endTime' : IDL.Nat,
  'createdAt' : Time,
  'score' : IDL.Float64,
  'videoUrl' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'owner' : IDL.Null,
  'user' : IDL.Null,
  'friend' : IDL.Null,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'banned' : IDL.Null,
  'inactive' : IDL.Null,
  'suspended' : IDL.Null,
});
export const YouTubeChannelAuth = IDL.Record({
  'channelName' : IDL.Text,
  'expiresAt' : Time,
  'channelId' : IDL.Text,
  'refreshToken' : IDL.Text,
  'accessToken' : IDL.Text,
});
export const GoogleOAuthCredentials = IDL.Record({
  'expiresAt' : Time,
  'refreshToken' : IDL.Text,
  'scope' : IDL.Text,
  'accessToken' : IDL.Text,
  'idToken' : IDL.Text,
  'tokenType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'status' : UserStatus,
  'youtubeAuth' : IDL.Opt(YouTubeChannelAuth),
  'name' : IDL.Text,
  'role' : UserRole,
  'googleOAuthCredentials' : IDL.Opt(GoogleOAuthCredentials),
});
export const SubmissionType = IDL.Variant({
  'BugReport' : IDL.Null,
  'FeatureRequest' : IDL.Null,
});
export const FeedbackSubmission = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'submitterPrincipal' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'submissionType' : SubmissionType,
  'submitterUserId' : IDL.Text,
});
export const TrendingClipAnalytics = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'scoreMetrics' : IDL.Float64,
  'trendingScore' : IDL.Float64,
});
export const ClipMetadata = IDL.Record({
  'title' : IDL.Text,
  'endTimestamp' : IDL.Nat,
  'startTimestamp' : IDL.Nat,
  'videoId' : IDL.Text,
});
export const YouTubePostResult = IDL.Record({
  'errorMessage' : IDL.Text,
  'success' : IDL.Bool,
  'videoUrl' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdminByUserId' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'connectYouTubeChannel' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
      [],
      [],
    ),
  'deleteClip' : IDL.Func([IDL.Text], [], []),
  'deleteFeedbackSubmission' : IDL.Func([IDL.Nat], [], []),
  'findRelatedClips' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'generateClipsAutomatically' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AutoGeneratedClipSuggestion)],
      ['query'],
    ),
  'generateDownloadVideoUrl' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Text],
      ['query'],
    ),
  'getAdminsAsAdmin' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllClips' : IDL.Func([IDL.Text], [IDL.Vec(VideoClip)], ['query']),
  'getAllUserRoles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserRole))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getClipById' : IDL.Func([IDL.Text], [VideoClip], ['query']),
  'getFeedbackSubmissions' : IDL.Func(
      [],
      [IDL.Vec(FeedbackSubmission)],
      ['query'],
    ),
  'getOwnRole' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
  'getTotalClipsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTrendingClips' : IDL.Func([], [IDL.Vec(VideoClip)], ['query']),
  'getTrendingClipsAnalytics' : IDL.Func(
      [],
      [IDL.Vec(TrendingClipAnalytics)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasGoogleOAuthCredentials' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isYouTubeChannelConnected' : IDL.Func([], [IDL.Bool], ['query']),
  'postClipToYouTube' : IDL.Func([ClipMetadata], [YouTubePostResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveClip' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
      [IDL.Text],
      [],
    ),
  'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'storeGoogleOAuthCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitFeedback' : IDL.Func(
      [SubmissionType, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateUserStatus' : IDL.Func([IDL.Principal, UserStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AutoGeneratedClipSuggestion = IDL.Record({
    'title' : IDL.Text,
    'viralScore' : IDL.Float64,
    'endTimestamp' : IDL.Nat,
    'startTimestamp' : IDL.Nat,
  });
  const VideoClip = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'endTime' : IDL.Nat,
    'createdAt' : Time,
    'score' : IDL.Float64,
    'videoUrl' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'owner' : IDL.Null,
    'user' : IDL.Null,
    'friend' : IDL.Null,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'banned' : IDL.Null,
    'inactive' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const YouTubeChannelAuth = IDL.Record({
    'channelName' : IDL.Text,
    'expiresAt' : Time,
    'channelId' : IDL.Text,
    'refreshToken' : IDL.Text,
    'accessToken' : IDL.Text,
  });
  const GoogleOAuthCredentials = IDL.Record({
    'expiresAt' : Time,
    'refreshToken' : IDL.Text,
    'scope' : IDL.Text,
    'accessToken' : IDL.Text,
    'idToken' : IDL.Text,
    'tokenType' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'status' : UserStatus,
    'youtubeAuth' : IDL.Opt(YouTubeChannelAuth),
    'name' : IDL.Text,
    'role' : UserRole,
    'googleOAuthCredentials' : IDL.Opt(GoogleOAuthCredentials),
  });
  const SubmissionType = IDL.Variant({
    'BugReport' : IDL.Null,
    'FeatureRequest' : IDL.Null,
  });
  const FeedbackSubmission = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'submitterPrincipal' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'submissionType' : SubmissionType,
    'submitterUserId' : IDL.Text,
  });
  const TrendingClipAnalytics = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'scoreMetrics' : IDL.Float64,
    'trendingScore' : IDL.Float64,
  });
  const ClipMetadata = IDL.Record({
    'title' : IDL.Text,
    'endTimestamp' : IDL.Nat,
    'startTimestamp' : IDL.Nat,
    'videoId' : IDL.Text,
  });
  const YouTubePostResult = IDL.Record({
    'errorMessage' : IDL.Text,
    'success' : IDL.Bool,
    'videoUrl' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdminByUserId' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'connectYouTubeChannel' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
        [],
        [],
      ),
    'deleteClip' : IDL.Func([IDL.Text], [], []),
    'deleteFeedbackSubmission' : IDL.Func([IDL.Nat], [], []),
    'findRelatedClips' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'generateClipsAutomatically' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AutoGeneratedClipSuggestion)],
        ['query'],
      ),
    'generateDownloadVideoUrl' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Text],
        ['query'],
      ),
    'getAdminsAsAdmin' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllClips' : IDL.Func([IDL.Text], [IDL.Vec(VideoClip)], ['query']),
    'getAllUserRoles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserRole))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getClipById' : IDL.Func([IDL.Text], [VideoClip], ['query']),
    'getFeedbackSubmissions' : IDL.Func(
        [],
        [IDL.Vec(FeedbackSubmission)],
        ['query'],
      ),
    'getOwnRole' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
    'getTotalClipsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTrendingClips' : IDL.Func([], [IDL.Vec(VideoClip)], ['query']),
    'getTrendingClipsAnalytics' : IDL.Func(
        [],
        [IDL.Vec(TrendingClipAnalytics)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasGoogleOAuthCredentials' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isYouTubeChannelConnected' : IDL.Func([], [IDL.Bool], ['query']),
    'postClipToYouTube' : IDL.Func([ClipMetadata], [YouTubePostResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveClip' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
        [IDL.Text],
        [],
      ),
    'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'storeGoogleOAuthCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitFeedback' : IDL.Func(
        [SubmissionType, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateUserStatus' : IDL.Func([IDL.Principal, UserStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };