/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'id' : string,
  'action' : string,
  'userPrincipal' : string,
  'timestamp' : Time,
}
export interface AdminMessage {
  'id' : string,
  'body' : string,
  'toUserId' : string,
  'sentAt' : Time,
  'toPrincipal' : string,
  'fromUserId' : string,
  'fromPrincipal' : string,
}
export interface AutoGeneratedClipSuggestion {
  'title' : string,
  'viralScore' : number,
  'endTimestamp' : bigint,
  'startTimestamp' : bigint,
}
export interface ClipMetadata {
  'title' : string,
  'endTimestamp' : bigint,
  'startTimestamp' : bigint,
  'videoId' : string,
}
export interface ContentEntry {
  'id' : string,
  'title' : string,
  'body' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
}
export type ExternalBlob = Uint8Array;
export interface FeedbackSubmission {
  'id' : bigint,
  'title' : string,
  'submitterPrincipal' : string,
  'description' : string,
  'timestamp' : bigint,
  'submissionType' : SubmissionType,
  'submitterUserId' : string,
}
export interface GoogleOAuthCredentials {
  'expiresAt' : Time,
  'refreshToken' : string,
  'scope' : string,
  'accessToken' : string,
  'idToken' : string,
  'tokenType' : string,
}
export interface ScheduledUpload {
  'id' : string,
  'clipId' : string,
  'createdAt' : Time,
  'scheduledAt' : Time,
}
export type SubmissionType = { 'BugReport' : null } |
  { 'FeatureRequest' : null };
export interface SystemControlResult { 'message' : string, 'success' : boolean }
export type SystemStatus = { 'restarting' : null } |
  { 'shutting_down' : null } |
  { 'running' : null } |
  { 'paused' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TrendingClipAnalytics {
  'id' : string,
  'title' : string,
  'scoreMetrics' : number,
  'trendingScore' : number,
}
export interface UserProfile {
  'status' : UserStatus,
  'youtubeAuth' : [] | [YouTubeChannelAuth],
  'name' : string,
  'role' : UserRole,
  'profilePicture' : [] | [ExternalBlob],
  'googleOAuthCredentials' : [] | [GoogleOAuthCredentials],
}
export type UserRole = { 'admin' : null } |
  { 'owner' : null } |
  { 'user' : null } |
  { 'friend' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'active' : null } |
  { 'banned' : null } |
  { 'inactive' : null } |
  { 'suspended' : null };
export interface VideoClip {
  'id' : string,
  'startTime' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'endTime' : bigint,
  'createdAt' : Time,
  'score' : number,
  'videoUrl' : string,
}
export interface VideoUploadStats { 'hour' : bigint, 'count' : bigint }
export interface YouTubeChannelAuth {
  'channelName' : string,
  'expiresAt' : Time,
  'channelId' : string,
  'refreshToken' : string,
  'accessToken' : string,
}
export interface YouTubePostResult {
  'errorMessage' : string,
  'success' : boolean,
  'videoUrl' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdminByUserId' : ActorMethod<[string], undefined>,
  'addScheduledUpload' : ActorMethod<[string, Time], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'connectYouTubeChannel' : ActorMethod<
    [string, string, string, string, Time],
    undefined
  >,
  'createContentEntry' : ActorMethod<[string, string], string>,
  'deleteClip' : ActorMethod<[string], undefined>,
  'deleteClipsByUser' : ActorMethod<[string], undefined>,
  'deleteContentEntry' : ActorMethod<[string], undefined>,
  'deleteFeedbackSubmission' : ActorMethod<[bigint], undefined>,
  'deleteScheduledUpload' : ActorMethod<[string], undefined>,
  'findRelatedClips' : ActorMethod<[string], Array<string>>,
  'generateClipsAutomatically' : ActorMethod<
    [string],
    Array<AutoGeneratedClipSuggestion>
  >,
  'generateDownloadVideoUrl' : ActorMethod<[string, bigint, bigint], string>,
  'getActivityLogs' : ActorMethod<[], Array<ActivityLog>>,
  'getAdminsAsAdmin' : ActorMethod<[], Array<string>>,
  'getAllClips' : ActorMethod<[string], Array<VideoClip>>,
  'getAllUserRoles' : ActorMethod<[], Array<[Principal, UserRole]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getClickStats' : ActorMethod<[], bigint>,
  'getClipById' : ActorMethod<[string], VideoClip>,
  'getContentEntries' : ActorMethod<[], Array<ContentEntry>>,
  'getFeedbackSubmissions' : ActorMethod<[], Array<FeedbackSubmission>>,
  'getMyMessages' : ActorMethod<[string], Array<AdminMessage>>,
  'getMyScheduledUploads' : ActorMethod<[], Array<ScheduledUpload>>,
  'getOwnRole' : ActorMethod<[], [] | [UserRole]>,
  'getSystemStatus' : ActorMethod<[], SystemStatus>,
  'getTotalClipsCount' : ActorMethod<[], bigint>,
  'getTrendingClips' : ActorMethod<[], Array<VideoClip>>,
  'getTrendingClipsAnalytics' : ActorMethod<[], Array<TrendingClipAnalytics>>,
  'getUserMessages' : ActorMethod<[string], Array<AdminMessage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideosPerHour' : ActorMethod<[], Array<VideoUploadStats>>,
  'hasGoogleOAuthCredentials' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isYouTubeChannelConnected' : ActorMethod<[], boolean>,
  'logUserActivity' : ActorMethod<[string], undefined>,
  'postClipToYouTube' : ActorMethod<[ClipMetadata], YouTubePostResult>,
  'replyToMessage' : ActorMethod<[string, string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveClip' : ActorMethod<
    [string, string, string, bigint, bigint, number],
    string
  >,
  'sendMessage' : ActorMethod<[string, string, string, string], string>,
  'serverRestartAction' : ActorMethod<[], SystemControlResult>,
  'serverShutdownAction' : ActorMethod<[], SystemControlResult>,
  'setUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'storeGoogleOAuthCredentials' : ActorMethod<[string, string], undefined>,
  'submitFeedback' : ActorMethod<[SubmissionType, string, string], bigint>,
  'togglePauseSystem' : ActorMethod<[], SystemControlResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateContentEntry' : ActorMethod<[string, string, string], undefined>,
  'updateUserStatus' : ActorMethod<[Principal, UserStatus], undefined>,
  'uploadProfilePicture' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];