import { StrictMode, useState } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { RouterProvider, createRouter, createRoute, createRootRoute, Outlet } from '@tanstack/react-router';
import { Toaster } from '@/components/ui/sonner';
import Layout from './components/Layout';
import VideoUrlForm from './components/VideoUrlForm';
import YouTubePlayer from './components/YouTubePlayer';
import ClipTimestampControls from './components/ClipTimestampControls';
import ClipList from './components/ClipList';
import ClipSuggestions from './components/ClipSuggestions';
import AdminPanel from './components/AdminPanel';
import { useIsOwner } from './hooks/useIsOwner';
import { useInternetIdentity } from './hooks/useInternetIdentity';
import { Loader2 } from 'lucide-react';
import type { VideoClip, AutoGeneratedClipSuggestion } from './backend';

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      retry: 1,
    },
  },
});

function HomePage() {
  const [videoId, setVideoId] = useState<string>('');
  const [videoUrl, setVideoUrl] = useState<string>('');
  const [selectedClip, setSelectedClip] = useState<VideoClip | null>(null);
  const [suggestedClip, setSuggestedClip] = useState<{
    startTime: number;
    endTime: number;
    title: string;
  } | null>(null);
  const [aiGeneratedSuggestions, setAiGeneratedSuggestions] = useState<AutoGeneratedClipSuggestion[]>([]);

  const handleVideoSubmit = (url: string, id: string) => {
    setVideoUrl(url);
    setVideoId(id);
    setSelectedClip(null);
    setSuggestedClip(null);
    setAiGeneratedSuggestions([]);
  };

  const handleClipsGenerated = (clips: AutoGeneratedClipSuggestion[]) => {
    setAiGeneratedSuggestions(clips);
    setSuggestedClip(null);
  };

  const handleClipSelect = (clip: VideoClip) => {
    setSelectedClip(clip);
    setSuggestedClip(null);
    // Extract video ID from the clip's video URL
    const urlMatch = clip.videoUrl.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/)([^&\s]+)/);
    if (urlMatch) {
      setVideoId(urlMatch[1]);
      setVideoUrl(clip.videoUrl);
    }
  };

  const handleSuggestionSelect = (startTime: number, endTime: number, title: string) => {
    setSuggestedClip({ startTime, endTime, title });
    setSelectedClip(null);
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Main Content Area */}
        <div className="lg:col-span-2 space-y-6">
          <VideoUrlForm 
            onSubmit={handleVideoSubmit}
            onClipsGenerated={handleClipsGenerated}
          />
          
          {videoId && (
            <>
              <YouTubePlayer videoId={videoId} />
              <ClipTimestampControls 
                videoUrl={videoUrl}
                videoId={videoId}
                selectedClip={selectedClip}
                suggestedStartTime={suggestedClip?.startTime}
                suggestedEndTime={suggestedClip?.endTime}
                suggestedTitle={suggestedClip?.title}
              />
            </>
          )}
        </div>

        {/* Sidebar */}
        <div className="lg:col-span-1 space-y-6">
          <ClipSuggestions 
            onSelectSuggestion={handleSuggestionSelect}
            aiSuggestions={aiGeneratedSuggestions}
          />
          <ClipList onClipSelect={handleClipSelect} selectedClipId={selectedClip?.id} />
        </div>
      </div>
    </div>
  );
}

function AdminRoute() {
  const { identity } = useInternetIdentity();
  const { isOwner, isLoading, isFetched } = useIsOwner();
  
  const principalId = identity?.getPrincipal().toString() || 'Not authenticated';
  
  console.log('[AdminRoute] Render state:', {
    isAuthenticated: !!identity,
    principalId,
    isOwner,
    isLoading,
    isFetched,
    timestamp: new Date().toISOString()
  });

  // Show loading while checking authentication
  if (!identity || isLoading) {
    console.log('[AdminRoute] Showing loading state');
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="text-center space-y-4">
          <Loader2 className="h-8 w-8 animate-spin mx-auto text-primary" />
          <p className="text-muted-foreground">Checking admin access...</p>
        </div>
      </div>
    );
  }

  // Show access denied if not owner
  if (isFetched && !isOwner) {
    console.log('[AdminRoute] Access denied - not owner');
    return (
      <div className="min-h-screen flex items-center justify-center bg-background p-4">
        <div className="max-w-md w-full space-y-6 text-center">
          <div className="space-y-2">
            <h1 className="text-2xl font-bold text-foreground">Access Denied</h1>
            <p className="text-muted-foreground">
              You don't have permission to access the admin panel.
            </p>
          </div>
          
          <div className="p-4 bg-muted rounded-lg">
            <p className="text-sm text-muted-foreground mb-2">Your Principal ID:</p>
            <code className="text-xs break-all bg-background p-2 rounded block">
              {principalId}
            </code>
          </div>
          
          <a
            href="/"
            className="inline-block px-6 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors"
          >
            Return to Home
          </a>
        </div>
      </div>
    );
  }

  // Show admin panel if owner
  console.log('[AdminRoute] Rendering AdminPanel');
  return <AdminPanel />;
}

const rootRoute = createRootRoute({
  component: () => (
    <Layout>
      <Outlet />
    </Layout>
  ),
});

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: HomePage,
});

const adminRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/admin',
  component: AdminRoute,
});

const routeTree = rootRoute.addChildren([indexRoute, adminRoute]);

const router = createRouter({ routeTree });

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

export default function App() {
  return (
    <StrictMode>
      <QueryClientProvider client={queryClient}>
        <RouterProvider router={router} />
        <Toaster />
      </QueryClientProvider>
    </StrictMode>
  );
}
