import { useEffect, useState } from 'react';
import { RouterProvider, createRouter, createRoute, createRootRoute, Outlet } from '@tanstack/react-router';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Toaster } from '@/components/ui/sonner';
import { useInternetIdentity } from './hooks/useInternetIdentity';
import { useGetCallerUserProfile } from './hooks/useQueries';
import Layout from './components/Layout';
import ProfileSetup from './components/ProfileSetup';
import VideoUrlForm from './components/VideoUrlForm';
import YouTubePlayer from './components/YouTubePlayer';
import ClipTimestampControls from './components/ClipTimestampControls';
import ClipList from './components/ClipList';
import ClipSuggestions from './components/ClipSuggestions';
import ChannelConnection from './components/ChannelConnection';
import AdminPanel from './components/AdminPanel';
import OAuthCallback from './pages/OAuthCallback';
import { Loader2 } from 'lucide-react';
import type { AutoGeneratedClipSuggestion, VideoClip } from './backend';

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      retry: 1,
    },
  },
});

function HomePage() {
  const { identity } = useInternetIdentity();
  const { data: userProfile, isLoading: profileLoading, isFetched } = useGetCallerUserProfile();
  const [videoUrl, setVideoUrl] = useState('');
  const [videoId, setVideoId] = useState('');
  const [showProfileSetup, setShowProfileSetup] = useState(false);
  const [aiSuggestions, setAiSuggestions] = useState<AutoGeneratedClipSuggestion[]>([]);
  const [selectedClip, setSelectedClip] = useState<VideoClip | null>(null);

  const isAuthenticated = !!identity;

  useEffect(() => {
    if (isAuthenticated && !profileLoading && isFetched && userProfile === null) {
      setShowProfileSetup(true);
    } else {
      setShowProfileSetup(false);
    }
  }, [isAuthenticated, profileLoading, isFetched, userProfile]);

  const handleVideoSubmit = (url: string, id: string) => {
    setVideoUrl(url);
    setVideoId(id);
    setAiSuggestions([]);
  };

  const handleClipsGenerated = (clips: AutoGeneratedClipSuggestion[]) => {
    setAiSuggestions(clips);
  };

  const handleSuggestionSelect = (startTime: number, endTime: number, title: string) => {
    // This would populate the clip creation form
    console.log('Selected suggestion:', { startTime, endTime, title });
  };

  const handleClipSelect = (clip: VideoClip) => {
    setSelectedClip(clip);
  };

  if (!isAuthenticated) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center space-y-4">
          <h1 className="text-4xl font-bold">Welcome to Beast Clipping</h1>
          <p className="text-muted-foreground">Please log in to continue</p>
        </div>
      </div>
    );
  }

  if (profileLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  if (showProfileSetup) {
    return <ProfileSetup onComplete={() => setShowProfileSetup(false)} />;
  }

  return (
    <div className="container mx-auto px-4 py-8 space-y-8">
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6">
          <VideoUrlForm onSubmit={handleVideoSubmit} onClipsGenerated={handleClipsGenerated} />
          
          {videoId && (
            <>
              <YouTubePlayer videoId={videoId} />
              <ClipTimestampControls videoUrl={videoUrl} videoId={videoId} />
            </>
          )}
          
          <ClipList onClipSelect={handleClipSelect} selectedClipId={selectedClip?.id} />
        </div>

        <div className="space-y-6">
          <ChannelConnection />
          <ClipSuggestions onSelectSuggestion={handleSuggestionSelect} aiSuggestions={aiSuggestions} />
        </div>
      </div>
    </div>
  );
}

function AdminPage() {
  return <AdminPanel />;
}

const rootRoute = createRootRoute({
  component: () => (
    <Layout>
      <Outlet />
    </Layout>
  ),
});

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: HomePage,
});

const adminRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/admin',
  component: AdminPage,
});

const oauthCallbackRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/oauth/callback',
  component: OAuthCallback,
});

const routeTree = rootRoute.addChildren([indexRoute, adminRoute, oauthCallbackRoute]);

const router = createRouter({ routeTree });

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

export default function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
      <Toaster />
    </QueryClientProvider>
  );
}
