import { useState } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ThemeProvider } from 'next-themes';
import { RouterProvider, createRouter, createRoute, createRootRoute, Outlet } from '@tanstack/react-router';
import Layout from './components/Layout';
import VideoUrlForm from './components/VideoUrlForm';
import YouTubePlayer from './components/YouTubePlayer';
import ClipTimestampControls from './components/ClipTimestampControls';
import ClipList from './components/ClipList';
import ClipSuggestions from './components/ClipSuggestions';
import AdminPanel from './components/AdminPanel';
import AdminErrorBoundary from './components/AdminErrorBoundary';
import { Toaster } from '@/components/ui/sonner';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useIsOwner } from './hooks/useIsOwner';
import { ShieldAlert } from 'lucide-react';
import type { Clip, AutoGeneratedClipSuggestion } from './backend';

const queryClient = new QueryClient();

function HomePage() {
  const [videoId, setVideoId] = useState<string>('');
  const [videoUrl, setVideoUrl] = useState<string>('');
  const [selectedClip, setSelectedClip] = useState<Clip | null>(null);
  const [suggestedClip, setSuggestedClip] = useState<{
    startTime: number;
    endTime: number;
    title: string;
  } | null>(null);
  const [aiGeneratedSuggestions, setAiGeneratedSuggestions] = useState<AutoGeneratedClipSuggestion[]>([]);

  const handleVideoSubmit = (url: string, id: string) => {
    setVideoUrl(url);
    setVideoId(id);
    setSelectedClip(null);
    setSuggestedClip(null);
    setAiGeneratedSuggestions([]);
  };

  const handleClipsGenerated = (clips: AutoGeneratedClipSuggestion[]) => {
    setAiGeneratedSuggestions(clips);
    setSuggestedClip(null);
  };

  const handleClipSelect = (clip: Clip) => {
    setSelectedClip(clip);
    setSuggestedClip(null);
    // Extract video ID from the clip's video URL
    const urlMatch = clip.videoUrl.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/)([^&\s]+)/);
    if (urlMatch) {
      setVideoId(urlMatch[1]);
      setVideoUrl(clip.videoUrl);
    }
  };

  const handleSuggestionSelect = (startTime: number, endTime: number, title: string) => {
    setSuggestedClip({ startTime, endTime, title });
    setSelectedClip(null);
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Main Content Area */}
        <div className="lg:col-span-2 space-y-6">
          <VideoUrlForm 
            onSubmit={handleVideoSubmit}
            onClipsGenerated={handleClipsGenerated}
          />
          
          {videoId && (
            <>
              <YouTubePlayer videoId={videoId} />
              <ClipTimestampControls 
                videoUrl={videoUrl}
                videoId={videoId}
                selectedClip={selectedClip}
                suggestedStartTime={suggestedClip?.startTime}
                suggestedEndTime={suggestedClip?.endTime}
                suggestedTitle={suggestedClip?.title}
              />
            </>
          )}
        </div>

        {/* Sidebar */}
        <div className="lg:col-span-1 space-y-6">
          <ClipSuggestions 
            onSelectSuggestion={handleSuggestionSelect}
            aiSuggestions={aiGeneratedSuggestions}
          />
          <ClipList onClipSelect={handleClipSelect} selectedClipId={selectedClip?.id} />
        </div>
      </div>
    </div>
  );
}

function AdminPage() {
  const { isOwner, isLoading } = useIsOwner();

  if (isLoading) {
    return (
      <div className="container mx-auto px-4 py-8">
        <Card>
          <CardContent className="py-12">
            <div className="text-center text-muted-foreground">
              <p>Checking permissions...</p>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (!isOwner) {
    return (
      <div className="container mx-auto px-4 py-8">
        <Card className="max-w-md mx-auto">
          <CardHeader>
            <div className="flex items-center gap-2 text-destructive">
              <ShieldAlert className="w-6 h-6" />
              <CardTitle>Access Denied</CardTitle>
            </div>
            <CardDescription>
              You do not have permission to access this page.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              Only the application owner can access the admin panel. If you believe this is an error, please contact the administrator.
            </p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <AdminErrorBoundary>
      <AdminPanel />
    </AdminErrorBoundary>
  );
}

// Create routes
const rootRoute = createRootRoute({
  component: () => (
    <Layout>
      <Outlet />
    </Layout>
  ),
});

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: HomePage,
});

const adminRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/admin',
  component: AdminPage,
});

const routeTree = rootRoute.addChildren([indexRoute, adminRoute]);

const router = createRouter({ routeTree });

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

export default function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <RouterProvider router={router} />
        <Toaster />
      </ThemeProvider>
    </QueryClientProvider>
  );
}
