import type { Principal } from "@icp-sdk/core/principal";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
export class ExternalBlob {
    getBytes(): Promise<Uint8Array<ArrayBuffer>>;
    getDirectURL(): string;
    static fromURL(url: string): ExternalBlob;
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob;
    withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob;
}
export interface SystemControlResult {
    message: string;
    success: boolean;
}
export interface ContentEntry {
    id: string;
    title: string;
    body: string;
    createdAt: Time;
    updatedAt: Time;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface YouTubeChannelAuth {
    channelName: string;
    expiresAt: Time;
    channelId: string;
    refreshToken: string;
    accessToken: string;
}
export interface AdminMessage {
    id: string;
    body: string;
    toUserId: string;
    sentAt: Time;
    toPrincipal: string;
    fromUserId: string;
    fromPrincipal: string;
}
export interface YouTubePostResult {
    errorMessage: string;
    success: boolean;
    videoUrl: string;
}
export interface AutoGeneratedClipSuggestion {
    title: string;
    viralScore: number;
    endTimestamp: bigint;
    startTimestamp: bigint;
}
export interface ClipMetadata {
    title: string;
    endTimestamp: bigint;
    startTimestamp: bigint;
    videoId: string;
}
export interface ActivityLog {
    id: string;
    action: string;
    userPrincipal: string;
    timestamp: Time;
}
export interface VideoClip {
    id: string;
    startTime: bigint;
    title: string;
    thumbnailUrl: string;
    endTime: bigint;
    createdAt: Time;
    score: number;
    videoUrl: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface VideoUploadStats {
    hour: bigint;
    count: bigint;
}
export interface TrendingClipAnalytics {
    id: string;
    title: string;
    scoreMetrics: number;
    trendingScore: number;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface FeedbackSubmission {
    id: bigint;
    title: string;
    submitterPrincipal: string;
    description: string;
    timestamp: bigint;
    submissionType: SubmissionType;
    submitterUserId: string;
}
export interface ScheduledUpload {
    id: string;
    clipId: string;
    createdAt: Time;
    scheduledAt: Time;
}
export interface GoogleOAuthCredentials {
    expiresAt: Time;
    refreshToken: string;
    scope: string;
    accessToken: string;
    idToken: string;
    tokenType: string;
}
export interface UserProfile {
    status: UserStatus;
    youtubeAuth?: YouTubeChannelAuth;
    name: string;
    role: UserRole;
    profilePicture?: ExternalBlob;
    googleOAuthCredentials?: GoogleOAuthCredentials;
}
export enum SubmissionType {
    BugReport = "BugReport",
    FeatureRequest = "FeatureRequest"
}
export enum SystemStatus {
    restarting = "restarting",
    shutting_down = "shutting_down",
    running = "running",
    paused = "paused"
}
export enum UserRole {
    admin = "admin",
    owner = "owner",
    user = "user",
    friend = "friend"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserStatus {
    active = "active",
    banned = "banned",
    inactive = "inactive",
    suspended = "suspended"
}
export interface backendInterface {
    addAdminByUserId(userId: string): Promise<void>;
    addScheduledUpload(clipId: string, scheduledAt: Time): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    connectYouTubeChannel(accessToken: string, refreshToken: string, channelId: string, channelName: string, expiresAt: Time): Promise<void>;
    createContentEntry(title: string, body: string): Promise<string>;
    deleteClip(clipId: string): Promise<void>;
    deleteClipsByUser(userId: string): Promise<void>;
    deleteContentEntry(id: string): Promise<void>;
    deleteFeedbackSubmission(id: bigint): Promise<void>;
    deleteScheduledUpload(entryId: string): Promise<void>;
    findRelatedClips(clipId: string): Promise<Array<string>>;
    generateClipsAutomatically(_youtubeVideoId: string): Promise<Array<AutoGeneratedClipSuggestion>>;
    generateDownloadVideoUrl(videoId: string, startTime: bigint, endTime: bigint): Promise<string>;
    getActivityLogs(): Promise<Array<ActivityLog>>;
    getAdminsAsAdmin(): Promise<Array<string>>;
    getAllClips(_searchText: string): Promise<Array<VideoClip>>;
    getAllUserRoles(): Promise<Array<[Principal, UserRole]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getClickStats(): Promise<bigint>;
    getClipById(clipId: string): Promise<VideoClip>;
    getContentEntries(): Promise<Array<ContentEntry>>;
    getFeedbackSubmissions(): Promise<Array<FeedbackSubmission>>;
    getMyMessages(fromUserId: string): Promise<Array<AdminMessage>>;
    getMyScheduledUploads(): Promise<Array<ScheduledUpload>>;
    getOwnRole(): Promise<UserRole | null>;
    getSystemStatus(): Promise<SystemStatus>;
    getTotalClipsCount(): Promise<bigint>;
    getTrendingClips(): Promise<Array<VideoClip>>;
    getTrendingClipsAnalytics(): Promise<Array<TrendingClipAnalytics>>;
    getUserMessages(userId: string): Promise<Array<AdminMessage>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideosPerHour(): Promise<Array<VideoUploadStats>>;
    hasGoogleOAuthCredentials(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isYouTubeChannelConnected(): Promise<boolean>;
    logUserActivity(action: string): Promise<void>;
    postClipToYouTube(clipMetadata: ClipMetadata): Promise<YouTubePostResult>;
    replyToMessage(originalMessageId: string, replyBody: string, fromUserId: string): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveClip(title: string, videoUrl: string, thumbnailUrl: string, startTime: bigint, endTime: bigint, score: number): Promise<string>;
    sendMessage(toPrincipal: string, toUserId: string, body: string, fromUserId: string): Promise<string>;
    serverRestartAction(): Promise<SystemControlResult>;
    serverShutdownAction(): Promise<SystemControlResult>;
    setUserRole(target: Principal, userRole: UserRole): Promise<void>;
    storeGoogleOAuthCredentials(authorizationCode: string, redirectUri: string): Promise<void>;
    submitFeedback(submissionType: SubmissionType, title: string, description: string): Promise<bigint>;
    togglePauseSystem(): Promise<SystemControlResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateContentEntry(id: string, title: string, body: string): Promise<void>;
    updateUserStatus(target: Principal, newStatus: UserStatus): Promise<void>;
    uploadProfilePicture(blob: ExternalBlob): Promise<void>;
}
