/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SystemControlResult {
    message: string;
    success: boolean;
}
export interface ContentEntry {
    id: string;
    title: string;
    body: string;
    createdAt: Time;
    updatedAt: Time;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MintedClip {
    clipId: string;
    title: string;
    mintedAt: Time;
    videoUrl: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface YouTubeChannelAuth {
    channelName: string;
    expiresAt: Time;
    channelId: string;
    refreshToken: string;
    accessToken: string;
}
export interface AdminMessage {
    id: string;
    body: string;
    toUserId: string;
    sentAt: Time;
    toPrincipal: string;
    fromUserId: string;
    fromPrincipal: string;
}
export interface YouTubePostResult {
    errorMessage: string;
    success: boolean;
    videoUrl: string;
}
export interface AutoGeneratedClipSuggestion {
    title: string;
    viralScore: number;
    endTimestamp: bigint;
    startTimestamp: bigint;
}
export interface ClipMetadata {
    title: string;
    endTimestamp: bigint;
    startTimestamp: bigint;
    videoId: string;
}
export interface ActivityLog {
    id: string;
    action: string;
    userPrincipal: string;
    timestamp: Time;
}
export interface VideoClip {
    id: string;
    startTime: bigint;
    title: string;
    thumbnailUrl: string;
    endTime: bigint;
    createdAt: Time;
    score: number;
    videoUrl: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface VideoUploadStats {
    hour: bigint;
    count: bigint;
}
export interface TrendingClipAnalytics {
    id: string;
    title: string;
    scoreMetrics: number;
    trendingScore: number;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface FeedbackSubmission {
    id: bigint;
    title: string;
    submitterPrincipal: string;
    description: string;
    timestamp: bigint;
    submissionType: SubmissionType;
    submitterUserId: string;
}
export interface ScheduledUpload {
    id: string;
    clipId: string;
    createdAt: Time;
    scheduledAt: Time;
}
export interface AdminLink {
    id: bigint;
    url: string;
    title: string;
    createdAt: Time;
    createdBy: Principal;
}
export interface Notification {
    id: bigint;
    notificationType: NotificationType;
    read: boolean;
    sender?: Principal;
    message: string;
    timestamp: Time;
}
export interface GoogleOAuthCredentials {
    expiresAt: Time;
    refreshToken: string;
    scope: string;
    accessToken: string;
    idToken: string;
    tokenType: string;
}
export interface UserProfile {
    status: UserStatus;
    youtubeAuth?: YouTubeChannelAuth;
    name: string;
    role: UserRole;
    profilePicture?: ExternalBlob;
    googleOAuthCredentials?: GoogleOAuthCredentials;
}
export enum NotificationType {
    system_announcement = "system_announcement",
    new_message = "new_message",
    clip_processed = "clip_processed",
    reaction = "reaction"
}
export enum SubmissionType {
    BugReport = "BugReport",
    FeatureRequest = "FeatureRequest"
}
export enum SystemStatus {
    restarting = "restarting",
    shutting_down = "shutting_down",
    running = "running",
    paused = "paused"
}
export enum UserRole {
    admin = "admin",
    owner = "owner",
    user = "user",
    friend = "friend"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserStatus {
    active = "active",
    banned = "banned",
    inactive = "inactive",
    suspended = "suspended"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAdminByUserId(userId: string): Promise<void>;
    addAdminLink(title: string, url: string): Promise<void>;
    addNotification(recipient: Principal, message: string, notificationType: NotificationType, sender: Principal | null): Promise<void>;
    addScheduledUpload(clipId: string, scheduledAt: Time): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    connectYouTubeChannel(accessToken: string, refreshToken: string, channelId: string, channelName: string, expiresAt: Time): Promise<void>;
    createContentEntry(title: string, body: string): Promise<string>;
    deleteAdminLink(linkId: bigint): Promise<void>;
    deleteClip(clipId: string): Promise<void>;
    deleteClipsByUser(userId: string): Promise<void>;
    deleteContentEntry(id: string): Promise<void>;
    deleteFeedbackSubmission(id: bigint): Promise<void>;
    deleteScheduledUpload(entryId: string): Promise<void>;
    findRelatedClips(clipId: string): Promise<Array<string>>;
    generateClipsAutomatically(_youtubeVideoId: string): Promise<Array<AutoGeneratedClipSuggestion>>;
    generateDownloadVideoUrl(videoId: string, startTime: bigint, endTime: bigint): Promise<string>;
    getActivityLogs(): Promise<Array<ActivityLog>>;
    getAdminLinks(): Promise<Array<AdminLink>>;
    getAdminsAsAdmin(): Promise<Array<string>>;
    getAllClips(_searchText: string): Promise<Array<VideoClip>>;
    getAllUserRoles(): Promise<Array<[Principal, UserRole]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getClickStats(): Promise<bigint>;
    getClipById(clipId: string): Promise<VideoClip>;
    getContentEntries(): Promise<Array<ContentEntry>>;
    getFeedbackSubmissions(): Promise<Array<FeedbackSubmission>>;
    getMintedClips(): Promise<Array<MintedClip>>;
    getMyMessages(fromUserId: string): Promise<Array<AdminMessage>>;
    getMyNotifications(): Promise<Array<Notification>>;
    getMyScheduledUploads(): Promise<Array<ScheduledUpload>>;
    getOwnRole(): Promise<UserRole | null>;
    getSystemStatus(): Promise<SystemStatus>;
    getTotalClipsCount(): Promise<bigint>;
    getTrendingClips(): Promise<Array<VideoClip>>;
    getTrendingClipsAnalytics(): Promise<Array<TrendingClipAnalytics>>;
    getUserMessages(userId: string): Promise<Array<AdminMessage>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideosPerHour(): Promise<Array<VideoUploadStats>>;
    hasGoogleOAuthCredentials(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isYouTubeChannelConnected(): Promise<boolean>;
    logUserActivity(action: string): Promise<void>;
    markNotificationsRead(): Promise<void>;
    mintClip(clipId: string, title: string, videoUrl: string): Promise<void>;
    postClipToYouTube(clipMetadata: ClipMetadata): Promise<YouTubePostResult>;
    replyToMessage(originalMessageId: string, replyBody: string, fromUserId: string): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveClip(title: string, videoUrl: string, thumbnailUrl: string, startTime: bigint, endTime: bigint, score: number): Promise<string>;
    sendMessage(toPrincipal: string, toUserId: string, body: string, fromUserId: string): Promise<string>;
    serverRestartAction(): Promise<SystemControlResult>;
    serverShutdownAction(): Promise<SystemControlResult>;
    setUserRole(target: Principal, userRole: UserRole): Promise<void>;
    storeGoogleOAuthCredentials(authorizationCode: string, redirectUri: string): Promise<void>;
    submitFeedback(submissionType: SubmissionType, title: string, description: string): Promise<bigint>;
    togglePauseSystem(): Promise<SystemControlResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAdminLink(linkId: bigint, url: string): Promise<void>;
    updateContentEntry(id: string, title: string, body: string): Promise<void>;
    updateUserStatus(target: Principal, newStatus: UserStatus): Promise<void>;
    uploadProfilePicture(blob: ExternalBlob): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, FeedbackSubmission as _FeedbackSubmission, GoogleOAuthCredentials as _GoogleOAuthCredentials, Notification as _Notification, NotificationType as _NotificationType, SubmissionType as _SubmissionType, SystemStatus as _SystemStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, UserStatus as _UserStatus, YouTubeChannelAuth as _YouTubeChannelAuth, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdminByUserId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminByUserId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminByUserId(arg0);
            return result;
        }
    }
    async addAdminLink(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminLink(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminLink(arg0, arg1);
            return result;
        }
    }
    async addNotification(arg0: Principal, arg1: string, arg2: NotificationType, arg3: Principal | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0, arg1, to_candid_NotificationType_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0, arg1, to_candid_NotificationType_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addScheduledUpload(arg0: string, arg1: Time): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addScheduledUpload(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addScheduledUpload(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async connectYouTubeChannel(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.connectYouTubeChannel(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.connectYouTubeChannel(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createContentEntry(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createContentEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContentEntry(arg0, arg1);
            return result;
        }
    }
    async deleteAdminLink(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdminLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdminLink(arg0);
            return result;
        }
    }
    async deleteClip(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClip(arg0);
            return result;
        }
    }
    async deleteClipsByUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClipsByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClipsByUser(arg0);
            return result;
        }
    }
    async deleteContentEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContentEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContentEntry(arg0);
            return result;
        }
    }
    async deleteFeedbackSubmission(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeedbackSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeedbackSubmission(arg0);
            return result;
        }
    }
    async deleteScheduledUpload(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScheduledUpload(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScheduledUpload(arg0);
            return result;
        }
    }
    async findRelatedClips(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.findRelatedClips(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findRelatedClips(arg0);
            return result;
        }
    }
    async generateClipsAutomatically(arg0: string): Promise<Array<AutoGeneratedClipSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateClipsAutomatically(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateClipsAutomatically(arg0);
            return result;
        }
    }
    async generateDownloadVideoUrl(arg0: string, arg1: bigint, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateDownloadVideoUrl(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateDownloadVideoUrl(arg0, arg1, arg2);
            return result;
        }
    }
    async getActivityLogs(): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLogs();
            return result;
        }
    }
    async getAdminLinks(): Promise<Array<AdminLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminLinks();
            return result;
        }
    }
    async getAdminsAsAdmin(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminsAsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminsAsAdmin();
            return result;
        }
    }
    async getAllClips(arg0: string): Promise<Array<VideoClip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClips(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClips(arg0);
            return result;
        }
    }
    async getAllUserRoles(): Promise<Array<[Principal, UserRole]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserRoles();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserRoles();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClickStats(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getClickStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClickStats();
            return result;
        }
    }
    async getClipById(arg0: string): Promise<VideoClip> {
        if (this.processError) {
            try {
                const result = await this.actor.getClipById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClipById(arg0);
            return result;
        }
    }
    async getContentEntries(): Promise<Array<ContentEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentEntries();
            return result;
        }
    }
    async getFeedbackSubmissions(): Promise<Array<FeedbackSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbackSubmissions();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbackSubmissions();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMintedClips(): Promise<Array<MintedClip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMintedClips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMintedClips();
            return result;
        }
    }
    async getMyMessages(arg0: string): Promise<Array<AdminMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMessages(arg0);
            return result;
        }
    }
    async getMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyScheduledUploads(): Promise<Array<ScheduledUpload>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyScheduledUploads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyScheduledUploads();
            return result;
        }
    }
    async getOwnRole(): Promise<UserRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnRole();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnRole();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemStatus(): Promise<SystemStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemStatus();
                return from_candid_SystemStatus_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemStatus();
            return from_candid_SystemStatus_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalClipsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalClipsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalClipsCount();
            return result;
        }
    }
    async getTrendingClips(): Promise<Array<VideoClip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingClips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingClips();
            return result;
        }
    }
    async getTrendingClipsAnalytics(): Promise<Array<TrendingClipAnalytics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingClipsAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingClipsAnalytics();
            return result;
        }
    }
    async getUserMessages(arg0: string): Promise<Array<AdminMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMessages(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideosPerHour(): Promise<Array<VideoUploadStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosPerHour();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosPerHour();
            return result;
        }
    }
    async hasGoogleOAuthCredentials(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasGoogleOAuthCredentials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasGoogleOAuthCredentials();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isYouTubeChannelConnected(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isYouTubeChannelConnected();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isYouTubeChannelConnected();
            return result;
        }
    }
    async logUserActivity(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logUserActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logUserActivity(arg0);
            return result;
        }
    }
    async markNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsRead();
            return result;
        }
    }
    async mintClip(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.mintClip(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintClip(arg0, arg1, arg2);
            return result;
        }
    }
    async postClipToYouTube(arg0: ClipMetadata): Promise<YouTubePostResult> {
        if (this.processError) {
            try {
                const result = await this.actor.postClipToYouTube(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postClipToYouTube(arg0);
            return result;
        }
    }
    async replyToMessage(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.replyToMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyToMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveClip(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: number): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveClip(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveClip(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async serverRestartAction(): Promise<SystemControlResult> {
        if (this.processError) {
            try {
                const result = await this.actor.serverRestartAction();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.serverRestartAction();
            return result;
        }
    }
    async serverShutdownAction(): Promise<SystemControlResult> {
        if (this.processError) {
            try {
                const result = await this.actor.serverShutdownAction();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.serverShutdownAction();
            return result;
        }
    }
    async setUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n46(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n46(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async storeGoogleOAuthCredentials(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeGoogleOAuthCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeGoogleOAuthCredentials(arg0, arg1);
            return result;
        }
    }
    async submitFeedback(arg0: SubmissionType, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(to_candid_SubmissionType_n49(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(to_candid_SubmissionType_n49(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async togglePauseSystem(): Promise<SystemControlResult> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePauseSystem();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePauseSystem();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAdminLink(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminLink(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminLink(arg0, arg1);
            return result;
        }
    }
    async updateContentEntry(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContentEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContentEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async updateUserStatus(arg0: Principal, arg1: UserStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserStatus(arg0, to_candid_UserStatus_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserStatus(arg0, to_candid_UserStatus_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadProfilePicture(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProfilePicture(await to_candid_ExternalBlob_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProfilePicture(await to_candid_ExternalBlob_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FeedbackSubmission_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedbackSubmission): FeedbackSubmission {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionType): SubmissionType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_SystemStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SystemStatus): SystemStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_YouTubeChannelAuth]): YouTubeChannelAuth | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GoogleOAuthCredentials]): GoogleOAuthCredentials | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRole]): UserRole | null {
    return value.length === 0 ? null : from_candid_UserRole_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _UserStatus;
    youtubeAuth: [] | [_YouTubeChannelAuth];
    name: string;
    role: _UserRole;
    profilePicture: [] | [_ExternalBlob];
    googleOAuthCredentials: [] | [_GoogleOAuthCredentials];
}): Promise<{
    status: UserStatus;
    youtubeAuth?: YouTubeChannelAuth;
    name: string;
    role: UserRole;
    profilePicture?: ExternalBlob;
    googleOAuthCredentials?: GoogleOAuthCredentials;
}> {
    return {
        status: from_candid_UserStatus_n20(_uploadFile, _downloadFile, value.status),
        youtubeAuth: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.youtubeAuth)),
        name: value.name,
        role: from_candid_UserRole_n15(_uploadFile, _downloadFile, value.role),
        profilePicture: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.profilePicture)),
        googleOAuthCredentials: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.googleOAuthCredentials))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    submitterPrincipal: string;
    description: string;
    timestamp: bigint;
    submissionType: _SubmissionType;
    submitterUserId: string;
}): {
    id: bigint;
    title: string;
    submitterPrincipal: string;
    description: string;
    timestamp: bigint;
    submissionType: SubmissionType;
    submitterUserId: string;
} {
    return {
        id: value.id,
        title: value.title,
        submitterPrincipal: value.submitterPrincipal,
        description: value.description,
        timestamp: value.timestamp,
        submissionType: from_candid_SubmissionType_n31(_uploadFile, _downloadFile, value.submissionType),
        submitterUserId: value.submitterUserId
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    notificationType: _NotificationType;
    read: boolean;
    sender: [] | [Principal];
    message: string;
    timestamp: _Time;
}): {
    id: bigint;
    notificationType: NotificationType;
    read: boolean;
    sender?: Principal;
    message: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        notificationType: from_candid_NotificationType_n36(_uploadFile, _downloadFile, value.notificationType),
        read: value.read,
        sender: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.sender)),
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserRole]): [Principal, UserRole] {
    return [
        value[0],
        from_candid_UserRole_n15(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    owner: null;
} | {
    user: null;
} | {
    friend: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "owner" in value ? UserRole.owner : "user" in value ? UserRole.user : "friend" in value ? UserRole.friend : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    banned: null;
} | {
    inactive: null;
} | {
    suspended: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "banned" in value ? UserStatus.banned : "inactive" in value ? UserStatus.inactive : "suspended" in value ? UserStatus.suspended : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BugReport: null;
} | {
    FeatureRequest: null;
}): SubmissionType {
    return "BugReport" in value ? SubmissionType.BugReport : "FeatureRequest" in value ? SubmissionType.FeatureRequest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    system_announcement: null;
} | {
    new_message: null;
} | {
    clip_processed: null;
} | {
    reaction: null;
}): NotificationType {
    return "system_announcement" in value ? NotificationType.system_announcement : "new_message" in value ? NotificationType.new_message : "clip_processed" in value ? NotificationType.clip_processed : "reaction" in value ? NotificationType.reaction : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    restarting: null;
} | {
    shutting_down: null;
} | {
    running: null;
} | {
    paused: null;
}): SystemStatus {
    return "restarting" in value ? SystemStatus.restarting : "shutting_down" in value ? SystemStatus.shutting_down : "running" in value ? SystemStatus.running : "paused" in value ? SystemStatus.paused : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserRole]>): Array<[Principal, UserRole]> {
    return value.map((x)=>from_candid_tuple_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeedbackSubmission>): Array<FeedbackSubmission> {
    return value.map((x)=>from_candid_FeedbackSubmission_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n34(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_NotificationType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): _NotificationType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_SubmissionType_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionType): _SubmissionType {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): _UserStatus {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: UserStatus;
    youtubeAuth?: YouTubeChannelAuth;
    name: string;
    role: UserRole;
    profilePicture?: ExternalBlob;
    googleOAuthCredentials?: GoogleOAuthCredentials;
}): Promise<{
    status: _UserStatus;
    youtubeAuth: [] | [_YouTubeChannelAuth];
    name: string;
    role: _UserRole;
    profilePicture: [] | [_ExternalBlob];
    googleOAuthCredentials: [] | [_GoogleOAuthCredentials];
}> {
    return {
        status: to_candid_UserStatus_n44(_uploadFile, _downloadFile, value.status),
        youtubeAuth: value.youtubeAuth ? candid_some(value.youtubeAuth) : candid_none(),
        name: value.name,
        role: to_candid_UserRole_n46(_uploadFile, _downloadFile, value.role),
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n48(_uploadFile, _downloadFile, value.profilePicture)) : candid_none(),
        googleOAuthCredentials: value.googleOAuthCredentials ? candid_some(value.googleOAuthCredentials) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): {
    active: null;
} | {
    banned: null;
} | {
    inactive: null;
} | {
    suspended: null;
} {
    return value == UserStatus.active ? {
        active: null
    } : value == UserStatus.banned ? {
        banned: null
    } : value == UserStatus.inactive ? {
        inactive: null
    } : value == UserStatus.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    owner: null;
} | {
    user: null;
} | {
    friend: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.owner ? {
        owner: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.friend ? {
        friend: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionType): {
    BugReport: null;
} | {
    FeatureRequest: null;
} {
    return value == SubmissionType.BugReport ? {
        BugReport: null
    } : value == SubmissionType.FeatureRequest ? {
        FeatureRequest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): {
    system_announcement: null;
} | {
    new_message: null;
} | {
    clip_processed: null;
} | {
    reaction: null;
} {
    return value == NotificationType.system_announcement ? {
        system_announcement: null
    } : value == NotificationType.new_message ? {
        new_message: null
    } : value == NotificationType.clip_processed ? {
        clip_processed: null
    } : value == NotificationType.reaction ? {
        reaction: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
