import type { Principal } from "@icp-sdk/core/principal";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
export interface AutoGeneratedClipSuggestion {
    title: string;
    viralScore: number;
    endTimestamp: bigint;
    startTimestamp: bigint;
}
export type Time = bigint;
export interface Clip {
    id: string;
    startTime: bigint;
    title: string;
    thumbnailUrl: string;
    endTime: bigint;
    createdAt: Time;
    score: number;
    videoUrl: string;
}
export interface TrendingClipAnalytics {
    id: string;
    title: string;
    scoreMetrics: number;
    trendingScore: number;
}
export interface backendInterface {
    deleteClip(clipId: string): Promise<void>;
    findRelatedClips(clipId: string): Promise<Array<string>>;
    generateClipsAutomatically(_youtubeVideoId: string): Promise<Array<AutoGeneratedClipSuggestion>>;
    getAllClips(): Promise<Array<Clip>>;
    getClipById(clipId: string): Promise<Clip>;
    getTotalClipsCount(): Promise<bigint>;
    getTrendingClips(): Promise<Array<Clip>>;
    getTrendingClipsAnalytics(): Promise<Array<TrendingClipAnalytics>>;
    isAdmin(_inputPrincipal: Principal): Promise<boolean>;
    saveClip(title: string, videoUrl: string, thumbnailUrl: string, startTime: bigint, endTime: bigint, score: number): Promise<string>;
}
