import type { Principal } from "@icp-sdk/core/principal";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
export interface AutoGeneratedClipSuggestion {
    title: string;
    viralScore: number;
    endTimestamp: bigint;
    startTimestamp: bigint;
}
export interface ClipMetadata {
    title: string;
    endTimestamp: bigint;
    startTimestamp: bigint;
    videoId: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface VideoClip {
    id: string;
    startTime: bigint;
    title: string;
    thumbnailUrl: string;
    endTime: bigint;
    createdAt: Time;
    score: number;
    videoUrl: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface TrendingClipAnalytics {
    id: string;
    title: string;
    scoreMetrics: number;
    trendingScore: number;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface YouTubeChannelAuth {
    channelName: string;
    expiresAt: Time;
    channelId: string;
    refreshToken: string;
    accessToken: string;
}
export interface YouTubePostResult {
    errorMessage: string;
    success: boolean;
    videoUrl: string;
}
export interface GoogleOAuthCredentials {
    expiresAt: Time;
    refreshToken: string;
    scope: string;
    accessToken: string;
    idToken: string;
    tokenType: string;
}
export interface UserProfile {
    status: UserStatus;
    youtubeAuth?: YouTubeChannelAuth;
    name: string;
    role: UserRole;
    googleOAuthCredentials?: GoogleOAuthCredentials;
}
export enum UserRole {
    admin = "admin",
    owner = "owner",
    user = "user",
    friend = "friend"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserStatus {
    active = "active",
    banned = "banned",
    inactive = "inactive",
    suspended = "suspended"
}
export interface backendInterface {
    addAdminByUserId(userId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    connectYouTubeChannel(accessToken: string, refreshToken: string, channelId: string, channelName: string, expiresAt: Time): Promise<void>;
    deleteClip(clipId: string): Promise<void>;
    findRelatedClips(clipId: string): Promise<Array<string>>;
    generateClipsAutomatically(_youtubeVideoId: string): Promise<Array<AutoGeneratedClipSuggestion>>;
    generateDownloadVideoUrl(videoId: string, startTime: bigint, endTime: bigint): Promise<string>;
    getAdminsAsAdmin(): Promise<Array<string>>;
    getAllClips(_searchText: string): Promise<Array<VideoClip>>;
    getAllUserRoles(): Promise<Array<[Principal, UserRole]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getClipById(clipId: string): Promise<VideoClip>;
    getOwnRole(): Promise<UserRole | null>;
    getTotalClipsCount(): Promise<bigint>;
    getTrendingClips(): Promise<Array<VideoClip>>;
    getTrendingClipsAnalytics(): Promise<Array<TrendingClipAnalytics>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasGoogleOAuthCredentials(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isYouTubeChannelConnected(): Promise<boolean>;
    postClipToYouTube(clipMetadata: ClipMetadata): Promise<YouTubePostResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveClip(title: string, videoUrl: string, thumbnailUrl: string, startTime: bigint, endTime: bigint, score: number): Promise<string>;
    setUserRole(target: Principal, userRole: UserRole): Promise<void>;
    storeGoogleOAuthCredentials(authorizationCode: string, redirectUri: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateUserStatus(target: Principal, newStatus: UserStatus): Promise<void>;
}
